
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-19T23:03:38-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ccc48624902c6756450d0ddfcc9352990d9f340",
 "version": "0.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
