
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-24T11:47:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3718f5825ac550e7c7dfaec1d9e9a080cac60b3",
 "version": "1.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
