
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-20T23:07:35+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "070082e37a86c7b51b3d39384d4a1d40d3fa195b",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
