# Generated by Django 2.2.5 on 2020-11-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_auto_20201114_1729"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="publication_date",
            field=models.DateTimeField(verbose_name="Дата размещения"),
        ),
    ]
