# Generated by Django 2.2.5 on 2020-11-28 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_locality_canter"),
        ("plans", "0003_auto_20201115_1115"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.Category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans_categories",
                        to="core.Department",
                        verbose_name="Ведомство",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория ведомства",
                "verbose_name_plural": "Категории ведомства",
                "unique_together": {("department", "category")},
            },
        ),
    ]
