# Generated by Django 2.2.5 on 2023-07-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_auto_20221025_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentcategory',
            name='department',
            field=models.ForeignKey(limit_choices_to={'status': 'IS_ACTIVE'}, on_delete=django.db.models.deletion.CASCADE, related_name='plans_categories', to='core.Department', verbose_name='Ведомство'),
        ),
    ]
