# coding: utf-8

"""
    Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference

    <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v12/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>   # noqa: E501

    The version of the OpenAPI document: v12
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from yahoo_search_api_v12.configuration import Configuration


class AssetServiceStructuredSnippetAsset(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'header': 'str',
        'review_header': 'str',
        'values': 'list[str]',
        'review_values': 'list[str]'
    }

    attribute_map = {
        'header': 'header',
        'review_header': 'reviewHeader',
        'values': 'values',
        'review_values': 'reviewValues'
    }

    def __init__(self, header=None, review_header=None, values=None, review_values=None, local_vars_configuration=None):  # noqa: E501
        """AssetServiceStructuredSnippetAsset - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._header = None
        self._review_header = None
        self._values = None
        self._review_values = None
        self.discriminator = None

        self.header = header
        self.review_header = review_header
        self.values = values
        self.review_values = review_values

    @property
    def header(self):
        """Gets the header of this AssetServiceStructuredSnippetAsset.  # noqa: E501

        <div lang=\"ja\">ヘッダーです。<br> ADDおよびSET時、このフィールドは必須となります。</div> <div lang=\"en\">Header.<br> This field is required in ADD and SET operation.</div>   # noqa: E501

        :return: The header of this AssetServiceStructuredSnippetAsset.  # noqa: E501
        :rtype: str
        """
        return self._header

    @header.setter
    def header(self, header):
        """Sets the header of this AssetServiceStructuredSnippetAsset.

        <div lang=\"ja\">ヘッダーです。<br> ADDおよびSET時、このフィールドは必須となります。</div> <div lang=\"en\">Header.<br> This field is required in ADD and SET operation.</div>   # noqa: E501

        :param header: The header of this AssetServiceStructuredSnippetAsset.  # noqa: E501
        :type: str
        """

        self._header = header

    @property
    def review_header(self):
        """Gets the review_header of this AssetServiceStructuredSnippetAsset.  # noqa: E501

        <div lang=\"ja\">審査中のヘッダーです。<br> このフィールドは、リクエストの際には無視されます。<br> 審査中の間のみ、レスポンスの際に返却されます。</div> <div lang=\"en\">Header on editorial review.<br> This field will be ignored on input.<br> It will be returned at the time of response only during the review.</div>   # noqa: E501

        :return: The review_header of this AssetServiceStructuredSnippetAsset.  # noqa: E501
        :rtype: str
        """
        return self._review_header

    @review_header.setter
    def review_header(self, review_header):
        """Sets the review_header of this AssetServiceStructuredSnippetAsset.

        <div lang=\"ja\">審査中のヘッダーです。<br> このフィールドは、リクエストの際には無視されます。<br> 審査中の間のみ、レスポンスの際に返却されます。</div> <div lang=\"en\">Header on editorial review.<br> This field will be ignored on input.<br> It will be returned at the time of response only during the review.</div>   # noqa: E501

        :param review_header: The review_header of this AssetServiceStructuredSnippetAsset.  # noqa: E501
        :type: str
        """

        self._review_header = review_header

    @property
    def values(self):
        """Gets the values of this AssetServiceStructuredSnippetAsset.  # noqa: E501

        <div lang=\"ja\">バリューです。<br> ADDおよびSET時、このフィールドは必須となります。</div> <div lang=\"en\">Value.<br> This field is required in ADD and SET operation.</div>   # noqa: E501

        :return: The values of this AssetServiceStructuredSnippetAsset.  # noqa: E501
        :rtype: list[str]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this AssetServiceStructuredSnippetAsset.

        <div lang=\"ja\">バリューです。<br> ADDおよびSET時、このフィールドは必須となります。</div> <div lang=\"en\">Value.<br> This field is required in ADD and SET operation.</div>   # noqa: E501

        :param values: The values of this AssetServiceStructuredSnippetAsset.  # noqa: E501
        :type: list[str]
        """

        self._values = values

    @property
    def review_values(self):
        """Gets the review_values of this AssetServiceStructuredSnippetAsset.  # noqa: E501

        <div lang=\"ja\">レビュー中のバリューです。<br> このフィールドは、リクエストの際には無視されます。<br> 審査中の間のみ、レスポンスの際に返却されます。</div> <div lang=\"en\">Value on editorial review.<br> This field will be ignored on input.<br> It will be returned at the time of response only during the review.</div>   # noqa: E501

        :return: The review_values of this AssetServiceStructuredSnippetAsset.  # noqa: E501
        :rtype: list[str]
        """
        return self._review_values

    @review_values.setter
    def review_values(self, review_values):
        """Sets the review_values of this AssetServiceStructuredSnippetAsset.

        <div lang=\"ja\">レビュー中のバリューです。<br> このフィールドは、リクエストの際には無視されます。<br> 審査中の間のみ、レスポンスの際に返却されます。</div> <div lang=\"en\">Value on editorial review.<br> This field will be ignored on input.<br> It will be returned at the time of response only during the review.</div>   # noqa: E501

        :param review_values: The review_values of this AssetServiceStructuredSnippetAsset.  # noqa: E501
        :type: list[str]
        """

        self._review_values = review_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssetServiceStructuredSnippetAsset):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AssetServiceStructuredSnippetAsset):
            return True

        return self.to_dict() != other.to_dict()
