# Generated by Django 2.2.5 on 2022-02-07 03:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modules.appeals_pos.models.file


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appeals_pos", "0004_auto_20220204_1106"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="appeals_pos",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "txt",
                                    "doc",
                                    "docx",
                                    "rtf",
                                    "xls",
                                    "xlsx",
                                    "pps",
                                    "ppt",
                                    "pptx",
                                    "odt",
                                    "ods",
                                    "pub",
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "bpm",
                                    "png",
                                    "tif",
                                    "gif",
                                    "pcx",
                                    "mp3",
                                    "wma",
                                    "avi",
                                    "mp4",
                                    "mkv",
                                    "wmv",
                                    "wma",
                                    "mov",
                                    "flv",
                                ]
                            ),
                            modules.appeals_pos.models.file.validate_file_size,
                        ],
                        verbose_name="Файл",
                    ),
                ),
                ("name", models.TextField(verbose_name="Имя файла")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appeals_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл",
                "verbose_name_plural": "Файлы",
            },
        ),
        migrations.CreateModel(
            name="Appeal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст обращения")),
                ("status", models.CharField(max_length=30, verbose_name="Статус")),
                (
                    "creation_date_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("address", models.TextField(verbose_name="Адрес")),
                (
                    "coordinates",
                    models.CharField(max_length=50, verbose_name="Координаты"),
                ),
                (
                    "to_publish",
                    models.BooleanField(
                        default=True, verbose_name="Согласие публикации на портале"
                    ),
                ),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="appeals",
                        to="appeals_pos.File",
                        verbose_name="Приложения",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="appeals_pos.Subcategory",
                        verbose_name="Подкатегория",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appeals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обращение",
                "verbose_name_plural": "Обращения",
            },
        ),
    ]
