# Generated by Django 2.2.5 on 2022-02-08 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appeals_pos", "0006_auto_20220207_1640"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appeal",
            name="status",
            field=models.CharField(
                default="MODERATION", max_length=30, verbose_name="Статус"
            ),
        ),
        migrations.CreateModel(
            name="AppealAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_type",
                    models.CharField(max_length=50, verbose_name="Тип ответа"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "reject_reason",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(verbose_name="Дата добавления")),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Кем создано",
                    ),
                ),
                (
                    "appeal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appeals_pos.Appeal",
                        verbose_name="Обращения",
                    ),
                ),
            ],
        ),
    ]
