# Generated by Django 2.2.5 on 2022-02-17 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appeals_pos", "0008_auto_20220211_1443"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appealanswer",
            options={
                "verbose_name": "Ответ обращение",
                "verbose_name_plural": "Ответы на обращения",
            },
        ),
        migrations.RemoveField(
            model_name="appealanswer",
            name="appeal",
        ),
        migrations.RemoveField(
            model_name="appealanswer",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="appealanswer",
            name="created_by",
        ),
        migrations.AddField(
            model_name="file",
            name="pos_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="Идентификатор ПОС"
            ),
        ),
        migrations.AlterField(
            model_name="appeal",
            name="status",
            field=models.CharField(
                choices=[
                    ("MODERATION", "Модерирование"),
                    ("MODERATION_REJECTED", "Отклонено"),
                    ("MODERATION_ACCEPTED", "На рассмотрении"),
                    ("IN_PROGRESS", "В работе"),
                    ("RESPONDED", "Получен ответ"),
                ],
                default="MODERATION",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
        migrations.CreateModel(
            name="AppealStateChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MODERATION", "Модерирование"),
                            ("MODERATION_REJECTED", "Отклонено"),
                            ("MODERATION_ACCEPTED", "На рассмотрении"),
                            ("IN_PROGRESS", "В работе"),
                            ("RESPONDED", "Получен ответ"),
                        ],
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="Дата добавления")),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Кем создано",
                    ),
                ),
                (
                    "appeal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="appeals_pos.Appeal",
                        verbose_name="Обращение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изменение состояния обращения",
                "verbose_name_plural": "Изменения состояний обращений",
            },
        ),
        migrations.AddField(
            model_name="appealanswer",
            name="appeal_state_change",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer",
                to="appeals_pos.AppealStateChange",
                verbose_name="Изменение состояния обращения",
            ),
            preserve_default=False,
        ),
    ]
