# Generated by Django 2.2.5 on 2022-02-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appeals_pos", "0012_appeal_locality"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="type",
            field=models.TextField(
                choices=[("IMAGE", "Изображение"), ("DOCUMENT", "Документ")],
                default="DOCUMENT",
                verbose_name="Тип файла",
            ),
        ),
    ]
