# Generated by Django 2.2.5 on 2022-02-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appeals_pos", "0013_file_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appeals_rules",
                    models.TextField(
                        blank=True, null=True, verbose_name="Правила подчаи обращений"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки",
                "verbose_name_plural": "Настройки",
            },
        ),
    ]
