# Generated by Django 2.2.5 on 2022-02-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appeals_pos", "0014_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="appeals_rules",
            field=models.TextField(
                blank=True, null=True, verbose_name="Правила подачи обращений"
            ),
        ),
    ]
