# Generated by Django 2.2.5 on 2022-03-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appeals_pos", "0015_auto_20220225_1452"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="default_category_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="",
                verbose_name="Картинка для категорий по умолчанию",
            ),
        ),
    ]
