# Generated by Django 2.2.5 on 2023-07-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals_pos', '0020_auto_20221025_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealFilingInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.TextField(unique=True, verbose_name='Идентификатор блока')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Инструкция "Подать обращение"',
                'verbose_name_plural': 'Инструкции "Подать обращение"',
            },
        ),
    ]
