# Generated by Django 2.2.5 on 2023-08-02 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appeals_pos', '0022_delete_appealfilinginstruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='appeals_pos.Subcategory', verbose_name='Подкатегория'),
        ),
    ]
