# Generated by Django 2.2.5 on 2023-10-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals_pos', '0027_auto_20231009_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='smev_status',
            field=models.CharField(choices=[('PREPARING', 'Подготовка к отправке в СМЭВ'), ('SMEV_ERR', 'Ошибка при отправке в СМЭВ'), ('WAITING_RESPONSE', 'Ожидание ответа от СМЭВ'), ('SUCCESS', 'Сообщение получено')], default='PREPARING', max_length=30, verbose_name='Статус сообщения СМЭВ'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('MODERATION', 'На модерации'), ('MODERATION_REJECTED', 'Отклонено'), ('MODERATION_ACCEPTED', 'На рассмотрении'), ('IN_PROGRESS', 'В работе'), ('RESPONDED', 'Получен ответ')], default='MODERATION', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='appealstatechange',
            name='status',
            field=models.CharField(choices=[('MODERATION', 'На модерации'), ('MODERATION_REJECTED', 'Отклонено'), ('MODERATION_ACCEPTED', 'На рассмотрении'), ('IN_PROGRESS', 'В работе'), ('RESPONDED', 'Получен ответ')], max_length=50, verbose_name='Статус'),
        ),
    ]
