# Generated by Django 2.2.5 on 2023-10-12 08:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals_pos', '0030_auto_20231012_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealanswer',
            name='files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Ссылки на файлы'),
        ),
    ]
