# Generated by Django 2.2.5 on 2023-10-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals_pos', '0031_appealanswer_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='smev_status',
            field=models.CharField(choices=[('PREPARING', 'Подготовка к отправке в ПОС'), ('SMEV_ERR', 'Ошибка при отправке в ПОС'), ('WAITING_RESPONSE', 'Ожидание ответа от ПОС'), ('SUCCESS', 'Обращение зарегистрировано в ПОС')], default='PREPARING', max_length=30, verbose_name='Статус сообщения СМЭВ'),
        ),
    ]
