# Generated by Django 2.2.5 on 2023-11-01 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appeals_pos', '0032_auto_20231023_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_id', models.CharField(max_length=1000, verbose_name='Идентификатор файла ПОС')),
                ('file_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Имя файла')),
                ('ftp_uuid', models.CharField(blank=True, max_length=1000, null=True, verbose_name='UUID файла для FTP')),
                ('ftp_username', models.CharField(blank=True, max_length=1000, null=True, verbose_name='FTP логин')),
                ('ftp_password', models.CharField(blank=True, max_length=1000, null=True, verbose_name='FTP пароль')),
                ('appeal_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='appeals_pos.AppealAnswer', verbose_name='Изменение состояния обращения')),
            ],
            options={
                'verbose_name': 'Файл из ПОС',
                'verbose_name_plural': 'Файлы из ПОС',
            },
        ),
    ]
