# Generated by Django 2.2.5 on 2023-11-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals_pos', '0033_appealattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='appeals_pos', verbose_name='Файл'),
        ),
    ]
