# Generated by Django 2.2.5 on 2020-06-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="end_date",
            field=models.DateField(verbose_name="Дата завершения голосования"),
        ),
        migrations.AlterField(
            model_name="vote",
            name="start_date",
            field=models.DateField(verbose_name="Дата начала голосования"),
        ),
    ]
