# Generated by Django 2.2.5 on 2020-07-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0003_auto_20200623_1317"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="brief_image",
            field=models.ImageField(
                help_text="(максимальный размер файла 5 МБ)",
                upload_to="",
                verbose_name="Изображение для карточки",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="(максимальный размер файла 5 МБ)",
                null=True,
                upload_to="",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="voteansweroption",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="(максимальный размер файла 5 МБ)",
                null=True,
                upload_to="",
                verbose_name="Вспомогательное изображение",
            ),
        ),
        migrations.AlterField(
            model_name="votequestion",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="(максимальный размер файла 5 МБ)",
                null=True,
                upload_to="",
                verbose_name="Вспомогательное изображение",
            ),
        ),
    ]
