# Generated by Django 2.2.5 on 2021-02-15 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0008_vote_reject_reason_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote",
            old_name="brief_image",
            new_name="brief_image_old",
        ),
        migrations.RenameField(
            model_name="vote",
            old_name="image",
            new_name="image_old",
        ),
        migrations.RenameField(
            model_name="voteansweroption",
            old_name="image",
            new_name="image_old",
        ),
        migrations.RenameField(
            model_name="votequestion",
            old_name="photo",
            new_name="photo_old",
        ),
    ]
