# Generated by Django 2.2.5 on 2021-02-15 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_category_image"),
        ("voting", "0009_auto_20210215_0848"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="brief_image",
            field=models.ForeignKey(
                default=1,
                help_text="(максимальный размер файла 5 МБ)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes_brief_images",
                to="core.File",
                verbose_name="Изображение для карточки",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vote",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="(максимальный размер файла 5 МБ)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes_images",
                to="core.File",
                verbose_name="Изображение",
            ),
        ),
        migrations.AddField(
            model_name="voteansweroption",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="(максимальный размер файла 5 МБ)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vote_answers_images",
                to="core.File",
                verbose_name="Вспомогательное изображение",
            ),
        ),
        migrations.AddField(
            model_name="votequestion",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                help_text="(максимальный размер файла 5 МБ)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vote_questions_images",
                to="core.File",
                verbose_name="Вспомогательное изображение",
            ),
        ),
    ]
