# Generated by Django 2.2.5 on 2021-02-15 01:50

from django.db import migrations


def migrate_images(apps, schema_editor):
    """
    Adds the Author object in Book.author to the
    many-to-many relationship in Book.authors
    """
    File = apps.get_model("core", "File")
    Vote = apps.get_model("voting", "Vote")
    VoteQuestion = apps.get_model("voting", "VoteQuestion")
    VoteAnswerOption = apps.get_model("voting", "VoteAnswerOption")

    for vote in Vote.objects.all():
        if vote.brief_image_old:
            file = File.objects.create(
                file=vote.brief_image_old,
                type="IMAGE",
                name="",
            )
            vote.brief_image = file
            vote.save()
        if vote.image_old:
            file = File.objects.create(
                file=vote.image_old,
                type="IMAGE",
                name="",
            )
            vote.image = file
            vote.save()

    for question in VoteQuestion.objects.all():
        if question.photo_old:
            file = File.objects.create(
                file=question.photo_old,
                type="IMAGE",
                name="",
            )
            question.photo = file
            question.save()

    for answer in VoteAnswerOption.objects.all():
        if answer.image_old:
            file = File.objects.create(
                file=answer.image_old,
                type="IMAGE",
                name="",
            )
            answer.image = file
            answer.save()


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0010_auto_20210215_0849"),
    ]

    operations = [
        migrations.RunPython(migrate_images),
    ]
