# Generated by Django 2.2.5 on 2021-02-15 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0011_auto_20210215_0850"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="brief_image_old",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="image_old",
        ),
        migrations.RemoveField(
            model_name="voteansweroption",
            name="image_old",
        ),
        migrations.RemoveField(
            model_name="votequestion",
            name="photo_old",
        ),
    ]
