# Generated by Django 2.2.5 on 2021-02-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0012_auto_20210215_0858"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="multi_locality_vote",
            field=models.BooleanField(
                default=True, verbose_name="Разрешить голосовать в нескольких МО"
            ),
        ),
    ]
