# Generated by Django 2.2.5 on 2021-02-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0013_vote_multi_locality_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="operator_reject_reason_text",
            field=models.TextField(
                blank=True, verbose_name="Причина отказа оператором"
            ),
        ),
    ]
