# Generated by Django 2.2.5 on 2021-02-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0015_vote_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
    ]
