# Generated by Django 2.2.5 on 2021-02-24 07:27

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0016_auto_20210219_1212"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="reject_reason_text_comment",
            field=models.TextField(
                blank=True, verbose_name="Причина отказа модератором. Комментарий"
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("CREATED", "Модерирование"),
                    ("MODERATION_ACCEPTED", "Согласовано"),
                    ("MODERATION_REJECTED", "Отклонено"),
                    ("OPERATOR_ACCEPTED", "Ожидает публикации"),
                    ("OPERATOR_REJECTED", "Отклонено"),
                    ("PUBLISHED", "Открыто"),
                    ("FINISHED", "Завершено"),
                ],
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
