# Generated by Django 2.2.5 on 2021-03-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0017_auto_20210224_1427"),
    ]

    operations = [
        migrations.AddField(
            model_name="voteansweroption",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AddField(
            model_name="votequestion",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядок"),
        ),
    ]
