# Generated by Django 2.2.5 on 2022-03-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0019_auto_20220315_1447"),
    ]

    operations = [
        migrations.AddField(
            model_name="voteansweroption",
            name="type",
            field=models.CharField(
                choices=[("OPTION", "Вариант выбора"), ("CUSTOM", "Свой вариант")],
                default="OPTION",
                max_length=50,
                verbose_name="Тип варианта ответа",
            ),
        ),
    ]
