# Generated by Django 2.2.5 on 2022-03-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0020_voteansweroption_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="votequestion",
            name="always_visible",
            field=models.BooleanField(
                default=False, verbose_name="Показывать независимо от ссылок"
            ),
        ),
    ]
