# Generated by Django 2.2.5 on 2022-06-06 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_curatorpermissions'),
        ('voting', '0023_auto_20220331_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalVotingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа участников локального голосования',
                'verbose_name_plural': 'Группы участников локального голосоввания',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VotingParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Участник голосования',
                'verbose_name_plural': 'Участники голосования',
                'ordering': ['last_name', 'first_name', 'email'],
            },
        ),
        migrations.AddIndex(
            model_name='votingparticipant',
            index=models.Index(fields=['email'], name='voting_voti_email_eeff6e_idx'),
        ),
        migrations.AddField(
            model_name='localvotinggroup',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Department', verbose_name='Министерство'),
        ),
        migrations.AddField(
            model_name='localvotinggroup',
            name='voting_participant',
            field=models.ManyToManyField(to='voting.VotingParticipant', verbose_name='Участник голосования'),
        ),
        migrations.AddIndex(
            model_name='localvotinggroup',
            index=models.Index(fields=['name'], name='voting_loca_name_96023d_idx'),
        ),
    ]
