# Generated by Django 2.2.5 on 2022-06-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0026_localvotinggroup_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localvotinggroup',
            name='vote',
        ),
    ]
