# Generated by Django 2.2.5 on 2022-07-07 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0028_vote_participants_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localvotinggroup',
            name='voting_participant',
        ),
        migrations.AddField(
            model_name='votingparticipant',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='voting.LocalVotingGroup', verbose_name='Группа голосования'),
        ),
    ]
