# Generated by Django 2.2.5 on 2022-10-04 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20220920_1209'),
        ('voting', '0033_auto_20221004_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votemunicipal',
            name='participants_groups',
        ),
        migrations.RemoveField(
            model_name='votemunicipal',
            name='vote_type',
        ),
        migrations.AddField(
            model_name='votemunicipal',
            name='municipality',
            field=models.ManyToManyField(blank=True, related_name='get_municipality', to='core.Municipality', verbose_name='Муниципальное образование'),
        ),
        migrations.AddField(
            model_name='votemunicipal',
            name='vote_category',
            field=models.ManyToManyField(blank=True, to='voting.VoteCategory', verbose_name='Категории участников голосования'),
        ),
        migrations.AlterField(
            model_name='votemunicipal',
            name='full_description_voting_issue',
            field=models.TextField(blank=True, verbose_name='Полное описание вопроса голосования'),
        ),
        migrations.AlterField(
            model_name='votemunicipal',
            name='limit_number_characters_free_response',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Ограничение на количество символов свободного ответа'),
        ),
        migrations.AlterField(
            model_name='votemunicipal',
            name='locality',
            field=models.ManyToManyField(blank=True, related_name='get_locality', to='core.Locality', verbose_name='Населенный пункт'),
        ),
        migrations.CreateModel(
            name='VoteMunicipalQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.TextField(default='', verbose_name='Краткое описание вопроса')),
                ('description', models.TextField(blank=True, default='', verbose_name='Полное описание вопроса')),
                ('is_custom_answer_allowed', models.BooleanField(blank=True, default=False, verbose_name='Возможен вариант пользователя')),
                ('is_multi_answer_allowed', models.BooleanField(blank=True, default=False, verbose_name='Несколько ответов')),
                ('max_answer_option_count', models.PositiveIntegerField(default=1, verbose_name='Максимальное количество вариантов ответов доступных пользователю')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('always_visible', models.BooleanField(default=False, verbose_name='Показывать независимо от ссылок')),
                ('photo', models.ForeignKey(blank=True, help_text='(максимальный размер файла 5 МБ)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_vote_municipal_questions_images', to='core.File', verbose_name='Вспомогательное изображение')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_municipal_questions', to='voting.VoteMunicipal', verbose_name='Голосование')),
            ],
            options={
                'verbose_name': 'Вопрос голосования',
                'verbose_name_plural': 'Вопросы голосования',
            },
        ),
        migrations.CreateModel(
            name='VoteMunicipalAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.TextField(default='', verbose_name='Краткое описание варианта ответа')),
                ('description', models.TextField(blank=True, default='', verbose_name='Полное описание варианта ответа')),
                ('next_question_order', models.IntegerField(blank=True, null=True, verbose_name='Порядок следующего вопроса')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('type', models.CharField(choices=[('OPTION', 'Вариант выбора'), ('CUSTOM', 'Свой вариант')], default='OPTION', max_length=50, verbose_name='Тип варианта ответа')),
                ('image', models.ForeignKey(blank=True, help_text='(максимальный размер файла 5 МБ)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_vote_municipal_answers_images', to='core.File', verbose_name='Вспомогательное изображение')),
                ('vote_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_municipal_answers', to='voting.VoteMunicipalQuestion', verbose_name='Вопрос голосования')),
            ],
            options={
                'verbose_name': 'Вариант ответа на вопрос',
                'verbose_name_plural': 'Варианты ответа на вопрос',
            },
        ),
    ]
