# Generated by Django 2.2.5 on 2022-10-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0034_auto_20221004_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemunicipal',
            name='age_restriction_finish',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Ограничение ДО какого возраста'),
        ),
        migrations.AlterField(
            model_name='votemunicipal',
            name='age_restriction_start',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Ограничение С какого возраста'),
        ),
    ]
