# Generated by Django 2.2.5 on 2022-10-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0035_auto_20221004_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemunicipal',
            name='municipality',
            field=models.ManyToManyField(related_name='get_municipality', to='core.Municipality', verbose_name='Муниципальное образование'),
        ),
    ]
