# Generated by Django 2.2.5 on 2022-10-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0039_auto_20221006_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votemunicipal',
            old_name='municipality',
            new_name='municipal_formation',
        ),
    ]
