# Generated by Django 2.2.5 on 2022-10-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0040_auto_20221006_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemunicipal',
            name='municipal_formation',
            field=models.ManyToManyField(related_name='get_municipality', to='core.Locality', verbose_name='Муниципальное образование'),
        ),
    ]
