# Generated by Django 2.2.5 on 2022-10-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0044_auto_20221006_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votemunicipal',
            old_name='hello',
            new_name='multi_municipality_vote',
        ),
    ]
