# Generated by Django 2.2.5 on 2022-10-07 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0045_auto_20221006_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemunicipalanswer',
            name='image',
            field=models.ForeignKey(blank=True, help_text='(максимальный размер файла 5 МБ)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_municipal_answers_images', to='core.File', verbose_name='Вспомогательное изображение'),
        ),
        migrations.AlterField(
            model_name='votemunicipalanswer',
            name='vote_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipal_answers', to='voting.VoteMunicipalQuestion', verbose_name='Вопрос голосования'),
        ),
        migrations.AlterField(
            model_name='votemunicipalquestion',
            name='photo',
            field=models.ForeignKey(blank=True, help_text='(максимальный размер файла 5 МБ)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_municipal_questions_images', to='core.File', verbose_name='Вспомогательное изображение'),
        ),
        migrations.AlterField(
            model_name='votemunicipalquestion',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipal_questions', to='voting.VoteMunicipal', verbose_name='Голосование'),
        ),
    ]
