# Generated by Django 2.2.5 on 2022-10-11 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20220920_1209'),
        ('voting', '0047_auto_20221011_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='votemunicipal',
            name='image',
            field=models.ForeignKey(blank=True, help_text='(максимальный размер файла 5 МБ)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipal_vote_image', to='core.File', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='voteregional',
            name='image',
            field=models.ForeignKey(blank=True, help_text='(максимальный размер файла 5 МБ)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regional_vote_image', to='core.File', verbose_name='Изображение'),
        ),
    ]
