# Generated by Django 2.2.5 on 2022-10-11 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0048_auto_20221011_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemunicipal',
            name='department',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Department', verbose_name='Инициатор голосования'),
        ),
    ]
