# Generated by Django 2.2.5 on 2022-10-13 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20221011_1559'),
        ('voting', '0055_auto_20221013_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermunicipalvote',
            name='answer_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.VoteRegionalAnswer', verbose_name='Вариант ответа'),
        ),
        migrations.AddField(
            model_name='usermunicipalvote',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipality', to='core.Municipality', verbose_name='Муниципальный округ'),
        ),
        migrations.AddField(
            model_name='usermunicipalvote',
            name='question_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.VoteRegionalQuestion', verbose_name='Вопрос голосования'),
        ),
        migrations.AlterField(
            model_name='usermunicipalvote',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.VoteMunicipalQuestion', verbose_name='Вопрос голосования'),
        ),
    ]
