# Generated by Django 2.2.5 on 2022-10-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0057_auto_20221013_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemunicipal',
            name='vote_category',
            field=models.ManyToManyField(blank=True, to='core.CategoryCitizen', verbose_name='Категории участников голосования'),
        ),
        migrations.AlterField(
            model_name='voteregional',
            name='vote_category',
            field=models.ManyToManyField(blank=True, to='core.CategoryCitizen', verbose_name='Категории участников голосования'),
        ),
    ]
