# Generated by Django 2.2.5 on 2022-10-14 09:44

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20221011_1559'),
        ('voting', '0058_auto_20221014_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название голосования')),
                ('start_date', models.DateField(verbose_name='Дата начала голосования')),
                ('end_date', models.DateField(verbose_name='Дата завершения голосования')),
                ('description_vote', models.TextField(blank=True, verbose_name='Описание голосования')),
                ('access_interim_results', models.BooleanField(blank=True, default=False, verbose_name='Доступ к просмотру промежуточных результатов голосования')),
                ('access_total_results', models.BooleanField(blank=True, default=False, verbose_name='Доступ к просмотру промежуточных результатов голосования')),
                ('is_opened', models.BooleanField(default=False, verbose_name='Открыто')),
                ('topic', models.TextField(blank=True, default='', verbose_name='Тема голосования')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('custom_url', models.TextField(blank=True, default='', verbose_name='Ссылка на внешний ресурс')),
                ('state', django_fsm.FSMField(choices=[('DRAFT', 'Черновик'), ('CREATED', 'Модерирование'), ('MODERATION_ACCEPTED', 'Согласовано'), ('MODERATION_REJECTED', 'Отклонено'), ('OPERATOR_ACCEPTED', 'Ожидает публикации'), ('OPERATOR_REJECTED', 'Отклонено'), ('PUBLISHED', 'Открыто'), ('FINISHED', 'Завершено')], max_length=50, verbose_name='Статус')),
                ('to_moderation_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата направления на модерацию')),
                ('moderation_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата модерациии')),
                ('operator_action_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата реакции оператора после модерации')),
                ('reject_reason_text', models.TextField(blank=True, verbose_name='Причина отказа модератором')),
                ('reject_reason_text_comment', models.TextField(blank=True, verbose_name='Причина отказа модератором. Комментарий')),
                ('operator_reject_reason_text', models.TextField(blank=True, verbose_name='Причина отказа оператором')),
                ('use_question_branches', models.BooleanField(default=False, verbose_name='Использовать механизм ветвления вопросов')),
                ('brief_image', models.ForeignKey(help_text='(максимальный размер файла 5 МБ)', on_delete=django.db.models.deletion.CASCADE, related_name='votes_local_brief_images', to='core.File', verbose_name='Изображение для карточки голосования')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Тематическая категория')),
                ('department', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Department', verbose_name='Инициатор голосования')),
                ('image', models.ForeignKey(blank=True, help_text='(максимальный размер файла 5 МБ)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_vote_image', to='core.File', verbose_name='Изображение')),
                ('locality', models.ManyToManyField(blank=True, related_name='vote_locality_local', to='core.Locality', verbose_name='Населенный пункт')),
                ('municipal_formation', models.ManyToManyField(related_name='vote_municipality_local', to='core.Municipality', verbose_name='Муниципальное образование')),
                ('participants_groups', models.ManyToManyField(blank=True, null=True, to='voting.LocalVotingGroup', verbose_name='Группы участников')),
            ],
            options={
                'verbose_name': 'Муниципальное голосование',
                'verbose_name_plural': 'Муниципальные голосования',
            },
        ),
        migrations.AlterModelOptions(
            name='votingparticipant',
            options={'ordering': ['last_name', 'first_name', 'email'], 'verbose_name': 'Участник локального голосования', 'verbose_name_plural': 'Участники локального голосования'},
        ),
        migrations.AddField(
            model_name='usermunicipalvote',
            name='local_groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_group', to='voting.LocalVotingGroup', verbose_name='Локальная группа'),
        ),
        migrations.CreateModel(
            name='VoteLocalQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.TextField(default='', verbose_name='Краткое описание вопроса')),
                ('description', models.TextField(blank=True, default='', verbose_name='Полное описание вопроса')),
                ('is_custom_answer_allowed', models.BooleanField(blank=True, default=False, verbose_name='Возможен вариант пользователя')),
                ('is_multi_answer_allowed', models.BooleanField(blank=True, default=False, verbose_name='Несколько ответов')),
                ('max_answer_option_count', models.PositiveIntegerField(default=1, verbose_name='Максимальное количество вариантов ответов доступных пользователю')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('always_visible', models.BooleanField(default=False, verbose_name='Показывать независимо от ссылок')),
                ('photo', models.ForeignKey(blank=True, help_text='(максимальный размер файла 5 МБ)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_local_questions_images', to='core.File', verbose_name='Вспомогательное изображение')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_questions', to='voting.VoteLocal', verbose_name='Голосование')),
            ],
            options={
                'verbose_name': 'Вопросы для локального голосования',
                'verbose_name_plural': 'Вопросы для локальных голосований',
            },
        ),
        migrations.CreateModel(
            name='VoteLocalAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.TextField(default='', verbose_name='Краткое описание варианта ответа')),
                ('description', models.TextField(blank=True, default='', verbose_name='Полное описание варианта ответа')),
                ('next_question_order', models.IntegerField(blank=True, null=True, verbose_name='Порядок следующего вопроса')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('type', models.CharField(choices=[('OPTION', 'Вариант выбора'), ('CUSTOM', 'Свой вариант')], default='OPTION', max_length=50, verbose_name='Тип варианта ответа')),
                ('image', models.ForeignKey(blank=True, help_text='(максимальный размер файла 5 МБ)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_local_answers_images', to='core.File', verbose_name='Вспомогательное изображение')),
                ('vote_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_answers', to='voting.VoteLocalQuestion', verbose_name='Вопрос голосования')),
            ],
            options={
                'verbose_name': 'Вариант ответа на вопрос локального голосования',
                'verbose_name_plural': 'Варианты ответа на вопросы локального голосований',
            },
        ),
        migrations.AddField(
            model_name='usermunicipalvote',
            name='answer_loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.VoteLocalAnswer', verbose_name='Вариант локального ответа'),
        ),
        migrations.AddField(
            model_name='usermunicipalvote',
            name='question_loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.VoteLocalQuestion', verbose_name='Вопрос локального голосования'),
        ),
        migrations.AddField(
            model_name='usermunicipalvote',
            name='vote_loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.VoteLocal', verbose_name='Локальное голосование'),
        ),
    ]
