# Generated by Django 2.2.5 on 2022-10-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0061_auto_20221020_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='votelocal',
            name='moderate',
            field=models.BooleanField(default=True, verbose_name='Нужна модерация?'),
        ),
    ]
