# Generated by Django 2.2.5 on 2022-10-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0064_auto_20221021_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationmoderationmechanism',
            name='date_operation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата операции'),
        ),
    ]
