# Generated by Django 2.2.5 on 2023-08-01 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0066_auto_20230723_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='vote_type',
        ),
    ]
