# Generated by Django 2.2.5 on 2023-08-04 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0068_auto_20230804_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Тематические категории'),
        ),
    ]
