# Generated by Django 2.2.5 on 2023-08-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0069_auto_20230804_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='bonus_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество бонусов'),
        ),
        migrations.AddField(
            model_name='vote',
            name='not_bonus_eligible',
            field=models.BooleanField(default=True, verbose_name='Не начислять бонусы'),
        ),
    ]
