# Generated by Django 2.2.5 on 2023-08-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0070_auto_20230811_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата завершения голосования'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала голосования'),
        ),
    ]
