# Generated by Django 2.2.5 on 2020-06-23 06:17

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="email",
            field=models.TextField(default="", verbose_name="Электронная почта"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="email_initiative_notification",
            field=models.BooleanField(
                default=True, verbose_name="Уведомления по инициативам по почте"
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="image",
            field=models.ImageField(default="", upload_to="", verbose_name="Иконка"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="locality",
            field=models.ManyToManyField(
                to="core.Locality", verbose_name="Муниципальные образования"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Department",
                verbose_name="Ведомство",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_initiative_notification",
            field=models.BooleanField(
                default=True, verbose_name="Уведомления по инициативам по почте"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="registration_locality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_registration",
                to="core.Locality",
                verbose_name="МО регистрации",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="residential_locality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_residential",
                to="core.Locality",
                verbose_name="МО проживания",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("ADMIN", "Администратор"),
                    ("OPERATOR", "Оператор"),
                    ("MODERATOR", "Модератор"),
                    ("SUPPORT", "Техподдержка"),
                    ("USER", "Пользователь"),
                ],
                default="USER",
                max_length=37,
                verbose_name="Роли",
            ),
            preserve_default=False,
        ),
    ]
