# Generated by Django 2.2.5 on 2020-06-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20200623_1317"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="esia_verified",
            field=models.BooleanField(
                default=False, verbose_name="Подтвержденный ЕСИА аккаунт"
            ),
        ),
    ]
