# Generated by Django 2.2.5 on 2020-07-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_esia_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                help_text="(максимальный размер файла 5 МБ)",
                upload_to="images/banners",
                verbose_name="Баннер",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="(максимальный размер файла 5 МБ)",
                null=True,
                upload_to="",
                verbose_name="Вспомогательное изображение",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="image",
            field=models.ImageField(
                help_text="(максимальный размер файла 5 МБ)",
                upload_to="",
                verbose_name="Иконка",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="(максимальный размер файла 5 МБ)",
                null=True,
                upload_to="images/news/",
                verbose_name="Изображение",
            ),
        ),
    ]
