# Generated by Django 2.2.5 on 2020-07-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0013_auto_20200710_1523"),
        ("core", "0004_auto_20200709_1520"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="additional_filtering",
            field=models.BooleanField(
                default=False,
                verbose_name="Отображать инициативы по выбранным муниципальным образованиям и категориям.",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                to="initiatives.InitiativeCategory",
                verbose_name="Категории для отображения",
            ),
        ),
    ]
