# Generated by Django 2.2.5 on 2020-10-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_locality_canter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="email_initiative_notification",
            field=models.BooleanField(
                default=True, verbose_name="Уведомления по почте"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_initiative_notification",
            field=models.BooleanField(
                default=True, verbose_name="Уведомления по почте"
            ),
        ),
    ]
