# Generated by Django 2.2.5 on 2020-12-05 05:12

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_locality_canter"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="inventory_locality",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_department",
                to="core.Locality",
                verbose_name="Муниципальное для инвентаризации",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("ADMIN", "Администратор"),
                    ("OPERATOR", "Оператор"),
                    ("MODERATOR", "Модератор"),
                    ("SUPPORT", "Техподдержка"),
                    ("USER", "Пользователь"),
                    (
                        "INVENTORY_LOCAL_GOVERNMENT",
                        "Инвентаризация. Орган местного самоуправления",
                    ),
                    (
                        "INVENTORY_EXECUTIVE_AUTHORITY",
                        "Инвентаризация. Орган исполнительной власти",
                    ),
                ],
                max_length=94,
                verbose_name="Роли",
            ),
        ),
    ]
