# Generated by Django 2.2.5 on 2021-02-09 08:50

from django.db import migrations


def migrate_images(apps, schema_editor):
    """
    Adds the Author object in Book.author to the
    many-to-many relationship in Book.authors
    """
    Category = apps.get_model("core", "Category")
    File = apps.get_model("core", "File")

    if not File.objects.filter(pk=1).exists():
        File.objects.create(
            file="",
            type="IMAGE",
            name="",
        )

    for category in Category.objects.all():
        if category.image:
            file = File.objects.create(
                file=category.image,
                type="IMAGE",
                name="",
            )
            category.images.add(file)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_category_images"),
    ]

    operations = [
        migrations.RunPython(migrate_images),
    ]
