# Generated by Django 2.2.5 on 2021-02-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_auto_20210209_1550"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
    ]
