# Generated by Django 2.2.5 on 2021-02-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="locality",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядок"),
        ),
    ]
