# Generated by Django 2.2.5 on 2021-08-18 04:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_auto_20210813_1607"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("ADMIN", "Администратор"),
                    ("OPERATOR", "Оператор"),
                    ("MODERATOR", "Модератор"),
                    ("SUPPORT", "Техподдержка"),
                    ("USER", "Пользователь"),
                    (
                        "INVENTORY_LOCAL_GOVERNMENT",
                        "Инвентаризация. Орган местного самоуправления",
                    ),
                    (
                        "INVENTORY_EXECUTIVE_AUTHORITY",
                        "Инвентаризация. Орган исполнительной власти",
                    ),
                    ("OPERATOR_OPINION", "Обратная связь. Оператор"),
                ],
                max_length=111,
                verbose_name="Роли",
            ),
        ),
    ]
