# Generated by Django 2.2.5 on 2021-10-25 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_auto_20211022_1525"),
        ("core", "0020_auto_20210915_1052"),
    ]

    operations = []
