# Generated by Django 2.2.5 on 2022-01-11 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_auto_20220111_1212"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectinfo",
            name="video",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Video",
                verbose_name="Видео",
            ),
        ),
    ]
