# Generated by Django 2.2.5 on 2022-02-28 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_auto_20220228_1450"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="video",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.Video",
                verbose_name="Видео",
            ),
        ),
    ]
