# Generated by Django 2.2.5 on 2022-04-08 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_news_is_public"),
    ]

    operations = [
        migrations.CreateModel(
            name="InhabitedLocality",
            fields=[],
            options={
                "verbose_name": "Населенный пункт",
                "verbose_name_plural": "Населенные пункты",
                "ordering": ["name"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.locality",),
        ),
        migrations.CreateModel(
            name="Municipality",
            fields=[],
            options={
                "verbose_name": "Муниципальное образование",
                "verbose_name_plural": "Муниципальные образования",
                "ordering": ["name"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.locality",),
        ),
        migrations.AlterModelOptions(
            name="locality",
            options={
                "ordering": ["name"],
                "verbose_name": "Населенный пункт",
                "verbose_name_plural": "Населенные пункты",
            },
        ),
        migrations.AlterField(
            model_name="locality",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="localities",
                to="core.Municipality",
                verbose_name="Муниципальное образование",
            ),
        ),
        migrations.AlterField(
            model_name="locality",
            name="type",
            field=models.IntegerField(
                choices=[
                    (10, "Муниципальный район"),
                    (70, "Муниципальный округ"),
                    (30, "Городской округ"),
                    (20, "Населенный пункт"),
                    (40, "Город"),
                    (50, "Поселок городского типа"),
                    (60, "Поселок"),
                ],
                verbose_name="Тип",
            ),
        ),
    ]
