# Generated by Django 2.2.5 on 2022-04-11 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_department_parent'),
        ('core', '0032_auto_20220406_1233'),
    ]

    operations = [
    ]
