# Generated by Django 2.2.5 on 2022-04-11 08:22

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_merge_20220411_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация бонусной программы', 'verbose_name_plural': 'Организации бонусной программы'},
        ),
        migrations.AlterField(
            model_name='activecitizenmodule',
            name='display_name',
            field=models.CharField(blank=True, choices=[('voting', '2. Голосования'), ('initiatives', '3. Инициативы'), ('appeals', '4. Обращения граждан (Старое)'), ('cology', '7. Бонусная программа'), ('ap_works', '5. Карта ремонтных работ'), ('plans', '6. Планы'), ('inventory', 'Инвентаризация'), ('feedback', '8. Обратная связь'), ('appeals_pos', '4. Обращения граждан')], max_length=255, verbose_name='Отображаемое название'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ADMIN_MAIN', 'Администратор'), ('ADMIN_LKO', 'Администратор ЛКО'), ('OPERATOR_MAIN', 'Оператор'), ('OPERATOR_LKO', 'Оператор ЛКО'), ('MODERATOR', 'Модератор'), ('SUPPORT', 'Техподдержка'), ('USER', 'Пользователь'), ('ORGANIZER', 'Организатор'), ('PARTNER', 'Партнер'), ('SECRETARY', 'Пресс-секретарь'), ('CURATOR', 'Куратор'), ('INVENTORY_LOCAL_GOVERNMENT', 'Инвентаризация. Орган местного самоуправления'), ('INVENTORY_EXECUTIVE_AUTHORITY', 'Инвентаризация. Орган исполнительной власти'), ('OPERATOR_OPINION', 'Обратная связь. Оператор')], max_length=180, verbose_name='Роли'),
        ),
    ]
