# Generated by Django 2.2.5 on 2022-04-11 08:25

from django.db import migrations


def migrate_roles(apps, schema_editor):
    User = apps.get_model('core', 'User')
    User.objects.filter(roles__icontains='ADMIN').update(roles='ADMIN_MAIN')
    User.objects.filter(roles__icontains='OPERATOR').update(roles='OPERATOR_MAIN')


def migrate_roles_reverse(apps, schema_editor):
    User = apps.get_model('core', 'User')
    User.objects.filter(roles__icontains='ADMIN_MAIN').update(roles='ADMIN')
    User.objects.filter(roles='OPERATOR_MAIN').update(roles='OPERATOR')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20220411_1522'),
    ]

    operations = [
        migrations.RunPython(migrate_roles, migrate_roles_reverse)
    ]
