# Generated by Django 2.2.5 on 2022-04-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_migrate_users_for_new_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('IS_ACTIVE', 'Активно'), ('ARCHIVED', 'В арихве')], default='IS_ACTIVE', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='privacy_policy',
            field=models.TextField(blank=True, null=True, verbose_name='Политика использования персональных данных'),
        ),
    ]
