# Generated by Django 2.2.5 on 2022-04-22 10:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20220412_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Описание')),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif'])], verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='InstructionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf', 'xlsx', 'mp4', 'mov', 'mpeg4', 'avi'])], verbose_name='Файлы')),
            ],
            options={
                'verbose_name': 'Инструкция по работе в системе',
                'verbose_name_plural': 'Инструкции по работе в системе',
            },
        ),
        migrations.CreateModel(
            name='UserActionTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('subject', models.CharField(default='SYSTEM', max_length=255, verbose_name='Пользователь')),
                ('subject_roles', models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Роль')),
                ('subject_organization', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Организация')),
                ('module', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Объект операции')),
                ('object_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Наименование объекта операции')),
                ('operation_type', models.CharField(choices=[('CREATE', 'Добавление'), ('UPDATE', 'Изменение'), ('DELETE', 'Удаление'), ('OTHER', 'Прочее')], default='OTHER', max_length=255, verbose_name='Тип операции')),
                ('locality', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='МО')),
                ('value_before', models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Значение до изменений')),
                ('value_after', models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Значение после изменений')),
            ],
            options={
                'verbose_name': 'Действие пользователя',
                'verbose_name_plural': 'Действия пользователей',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RoleInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(choices=[('ADMIN_MAIN', 'Администратор'), ('ADMIN_LKO', 'Администратор ЛКО'), ('OPERATOR_MAIN', 'Оператор'), ('OPERATOR_LKO', 'Оператор ЛКО'), ('MODERATOR', 'Модератор'), ('SUPPORT', 'Техподдержка'), ('USER', 'Пользователь'), ('ORGANIZER', 'Организатор'), ('PARTNER', 'Партнер'), ('SECRETARY', 'Пресс-секретарь'), ('CURATOR', 'Куратор'), ('INVENTORY_LOCAL_GOVERNMENT', 'Инвентаризация. Орган местного самоуправления'), ('INVENTORY_EXECUTIVE_AUTHORITY', 'Инвентаризация. Орган исполнительной власти'), ('OPERATOR_OPINION', 'Обратная связь. Оператор')], unique=True, verbose_name='Роль пользователя')),
                ('instructions', models.ManyToManyField(blank=True, null=True, to='core.InstructionFile', verbose_name='Инструкции')),
            ],
            options={
                'verbose_name': 'Назначение инструкций по ролям пользователей',
                'verbose_name_plural': 'Назначения инструкций по ролям пользователей',
            },
        ),
        migrations.CreateModel(
            name='MainPageBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.TextField(unique=True, verbose_name='Идентификатор block')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Блок главной страницы',
                'verbose_name_plural': 'Блоки главной страницы',
            },
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Image', verbose_name='Изображение'),
        ),
    ]
