# Generated by Django 2.2.5 on 2022-04-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20220425_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminlkopermissions',
            options={'verbose_name': 'Дополнительные права пользователя для роли Администратор ЛКО', 'verbose_name_plural': 'Дополнительные права пользователя для роли Администратор ЛКО'},
        ),
    ]
