# Generated by Django 2.2.5 on 2022-04-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20220426_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpermissions',
            name='status',
            field=models.CharField(choices=[('IS_ACTIVE', 'Активен'), ('ARCHIVED', 'Архив')], default='IS_ACTIVE', max_length=255, verbose_name='Статус'),
        ),
    ]
