# Generated by Django 2.2.5 on 2022-04-28 10:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_subpermissions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinvite',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ADMIN_MAIN', 'Администратор'), ('ADMIN_LKO', 'Администратор ЛКО'), ('OPERATOR_MAIN', 'Оператор'), ('OPERATOR_LKO', 'Оператор ЛКО'), ('MODERATOR', 'Модератор'), ('SUPPORT', 'Техподдержка'), ('USER', 'Пользователь'), ('ORGANIZER', 'Организатор'), ('PARTNER', 'Партнер'), ('SECRETARY', 'Пресс-секретарь'), ('CURATOR', 'Куратор'), ('INVENTORY_LOCAL_GOVERNMENT', 'Инвентаризация. Орган местного самоуправления'), ('INVENTORY_EXECUTIVE_AUTHORITY', 'Инвентаризация. Орган исполнительной власти'), ('OPERATOR_OPINION', 'Обратная связь. Оператор')], max_length=180, null=True, verbose_name='Роли'),
        ),
    ]
