# Generated by Django 2.2.5 on 2022-05-11 03:34

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('map_works', '0004_departmentcategory'),
        ('initiatives', '0016_initiativeinstruction'),
        ('plans', '0004_departmentcategory'),
        ('core', '0043_mailinvite_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentSubPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules_permissions', multiselectfield.db.fields.MultiSelectField(choices=[('MAP_WORKS', 'Карты'), ('PLANS', 'Планы'), ('VOTING', 'Голосования'), ('INITIATIVES', 'Инициативы')], max_length=34, verbose_name='Права модулей')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_permissions', to='core.Department', verbose_name='Организация')),
                ('initiative_categories', models.ManyToManyField(blank=True, related_name='department_initiatives_categories_permissions', to='initiatives.InitiativeCategory', verbose_name='Доступные категории инициатив')),
                ('map_works_categories', models.ManyToManyField(blank=True, related_name='department_map_works_categories_permissions', to='map_works.WorkCategory', verbose_name='Доступные категории карт')),
                ('plans_categories', models.ManyToManyField(blank=True, related_name='department_plans_categories_permissions', to='plans.Category', verbose_name='Доступные категории планов')),
                ('voting_categories', models.ManyToManyField(blank=True, related_name='department_voting_categories_permissions', to='core.Category', verbose_name='Доступные категории голосований')),
            ],
            options={
                'verbose_name': 'Дополнительные права для организации',
                'verbose_name_plural': 'Дополнительные права для организаций',
            },
        ),
    ]
