# Generated by Django 2.2.5 on 2022-06-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_merge_20220601_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpermissions',
            name='position',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='subpermissions',
            name='sub_phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Добавочный номер'),
        ),
    ]
