# Generated by Django 2.2.5 on 2022-08-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20220803_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractiontracking',
            name='value_after',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Значение после изменений'),
        ),
        migrations.AlterField(
            model_name='useractiontracking',
            name='value_before',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Значение до изменений'),
        ),
    ]
