# Generated by Django 2.2.5 on 2022-08-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20220817_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractiontracking',
            name='locality',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='МО'),
        ),
    ]
