# Generated by Django 2.2.5 on 2022-09-15 04:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20220829_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Описание')),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm', 'mp4', 'ogg'])], verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Аудио',
                'verbose_name_plural': 'Аудио',
            },
        ),
        migrations.AlterModelOptions(
            name='activecitizenmodule',
            options={'ordering': ('name',), 'verbose_name': 'Модуль портала', 'verbose_name_plural': 'Модули портала'},
        ),
        migrations.AlterField(
            model_name='activecitizenmodule',
            name='display_name',
            field=models.CharField(blank=True, choices=[('voting', 'Голосования'), ('initiatives', 'Инициативы'), ('appeals_pos', 'Обращения граждан'), ('ecology', 'Бонусная программа'), ('map_works', 'Карта ремонтных работ'), ('plans', 'Планы'), ('feedback', 'Обратная связь'), ('news', 'Новости'), ('about_project', 'О проекте')], max_length=255, verbose_name='Отображаемое название'),
        ),
        migrations.AlterField(
            model_name='activecitizenmodule',
            name='name',
            field=models.CharField(choices=[('voting', 'voting'), ('initiatives', 'initiatives'), ('appeals_pos', 'appeals_pos'), ('ecology', 'ecology'), ('map_works', 'map_works'), ('plans', 'plans'), ('feedback', 'feedback'), ('news', 'news'), ('about_project', 'about_project')], max_length=100, unique=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='news',
            name='audio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Audio', verbose_name='Аудио'),
        ),
    ]
