# Generated by Django 2.2.5 on 2022-10-20 02:31

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20221019_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=embed_video.fields.EmbedVideoField(verbose_name='Текст новости'),
        ),
    ]
