# Generated by Django 2.2.5 on 2023-07-18 14:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20221020_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinvite',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ADMIN_MAIN', 'Администратор'), ('ADMIN_LKO', 'Администратор ЛКО'), ('OPERATOR_MAIN', 'Оператор'), ('MODERATOR', 'Модератор'), ('SUPPORT', 'Техподдержка'), ('USER', 'Пользователь'), ('OPERATOR_OPINION', 'Обратная связь. Оператор')], max_length=74, null=True, verbose_name='Роли'),
        ),
        migrations.AlterField(
            model_name='roleinstruction',
            name='role',
            field=models.TextField(choices=[('ADMIN_MAIN', 'Администратор'), ('ADMIN_LKO', 'Администратор ЛКО'), ('OPERATOR_MAIN', 'Оператор'), ('MODERATOR', 'Модератор'), ('SUPPORT', 'Техподдержка'), ('USER', 'Пользователь'), ('OPERATOR_OPINION', 'Обратная связь. Оператор')], unique=True, verbose_name='Роль пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ADMIN_MAIN', 'Администратор'), ('ADMIN_LKO', 'Администратор ЛКО'), ('OPERATOR_MAIN', 'Оператор'), ('MODERATOR', 'Модератор'), ('SUPPORT', 'Техподдержка'), ('USER', 'Пользователь'), ('OPERATOR_OPINION', 'Обратная связь. Оператор')], max_length=74, verbose_name='Роли'),
        ),
    ]
