# Generated by Django 2.2.5 on 2023-07-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20230718_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
