# Generated by Django 2.2.5 on 2023-07-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20230720_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpermissions',
            name='status',
        ),
    ]
