# Generated by Django 2.2.5 on 2023-07-21 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20230721_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'IS_ACTIVE'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Department', verbose_name='Организации, к которым пользователь имеет доступ'),
        ),
    ]
