# Generated by Django 2.2.5 on 2023-07-24 02:26

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appeals_pos', '0021_appealfilinginstruction'),
        ('ecology', '0044_auto_20211122_1500'),
        ('core', '0067_auto_20230723_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentsubpermissions',
            name='appeals_categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='department_appeals_categories_permissions', to='appeals_pos.Category', verbose_name='Доступные категории проблематик'),
        ),
        migrations.AddField(
            model_name='departmentsubpermissions',
            name='encouragement_categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='department_ecology_encouragement_categories_permission', to='ecology.GoodsNServicesItemCategory', verbose_name='Доступные категории поощрений'),
        ),
        migrations.AddField(
            model_name='departmentsubpermissions',
            name='suggestion_categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='department_ecology_suggestion_categories_permissions', to='ecology.EventCategory', verbose_name='Доступные категории предложений'),
        ),
        migrations.AlterField(
            model_name='curatorpermissions',
            name='modules_permissions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MAP_WORKS', 'Карты'), ('PLANS', 'Планы'), ('VOTING', 'Голосования'), ('INITIATIVES', 'Инициативы'), ('APPEALS', 'Проблематика'), ('ENCOURAGEMENTS', 'Поощрения'), ('SUGGESTIONS', 'Предложения')], max_length=69, verbose_name='Права модулей'),
        ),
        migrations.AlterField(
            model_name='departmentsubpermissions',
            name='modules_permissions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MAP_WORKS', 'Карты'), ('PLANS', 'Планы'), ('VOTING', 'Голосования'), ('INITIATIVES', 'Инициативы'), ('APPEALS', 'Проблематика'), ('ENCOURAGEMENTS', 'Поощрения'), ('SUGGESTIONS', 'Предложения')], max_length=69, verbose_name='Права модулей'),
        ),
        migrations.AlterField(
            model_name='operatorlkopermissions',
            name='modules_permissions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MAP_WORKS', 'Карты'), ('PLANS', 'Планы'), ('VOTING', 'Голосования'), ('INITIATIVES', 'Инициативы'), ('APPEALS', 'Проблематика'), ('ENCOURAGEMENTS', 'Поощрения'), ('SUGGESTIONS', 'Предложения')], max_length=69, verbose_name='Права модулей'),
        ),
    ]
