# Generated by Django 2.2.5 on 2023-07-25 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20230724_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='site_module',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.ActiveCitizenModule', verbose_name='Блок страницы'),
        ),
        migrations.AlterField(
            model_name='activecitizenmodule',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отображаемое название'),
        ),
        migrations.AlterField(
            model_name='activecitizenmodule',
            name='name',
            field=models.CharField(choices=[('voting', 'Голосования'), ('initiatives', 'Инициативы'), ('appeals_pos', 'Обращения граждан'), ('ecology', 'Бонусная программа'), ('map_works', 'Карта ремонтных работ'), ('plans', 'Планы'), ('feedback', 'Обратная связь'), ('news', 'Новости'), ('about_project', 'О проекте'), ('new_module', 'Новый модуль')], max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='block_id',
            field=models.TextField(verbose_name='Идентификатор блока'),
        ),
    ]
