# Generated by Django 2.2.5 on 2023-07-25 05:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20230724_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.TextField(unique=True, verbose_name='Идентификатор блока')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('type', models.CharField(choices=[('INITIATIVE_SUBMISSION', 'Подать инициативу'), ('INITIATIVE_PROPOSAL', 'Предложить инициативу'), ('APPEAL_SUBMISSION', 'Подать обращение')], max_length=200, verbose_name='Тип инструкции')),
            ],
            options={
                'verbose_name': 'Инструкция',
                'verbose_name_plural': 'Инструкции',
            },
        ),
        migrations.AlterField(
            model_name='curatorpermissions',
            name='modules_permissions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MAP_WORKS', 'Карты'), ('PLANS', 'Планы'), ('VOTING', 'Голосования'), ('INITIATIVES', 'Инициативы'), ('APPEALS', 'Ваше мнение'), ('ENCOURAGEMENTS', 'Поощрения'), ('SUGGESTIONS', 'Предложения')], max_length=69, verbose_name='Права модулей'),
        ),
        migrations.AlterField(
            model_name='departmentsubpermissions',
            name='modules_permissions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MAP_WORKS', 'Карты'), ('PLANS', 'Планы'), ('VOTING', 'Голосования'), ('INITIATIVES', 'Инициативы'), ('APPEALS', 'Ваше мнение'), ('ENCOURAGEMENTS', 'Поощрения'), ('SUGGESTIONS', 'Предложения')], max_length=69, verbose_name='Права модулей'),
        ),
        migrations.AlterField(
            model_name='operatorlkopermissions',
            name='modules_permissions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MAP_WORKS', 'Карты'), ('PLANS', 'Планы'), ('VOTING', 'Голосования'), ('INITIATIVES', 'Инициативы'), ('APPEALS', 'Ваше мнение'), ('ENCOURAGEMENTS', 'Поощрения'), ('SUGGESTIONS', 'Предложения')], max_length=69, verbose_name='Права модулей'),
        ),
    ]
