# Generated by Django 2.2.5 on 2023-07-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20230725_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectinfo',
            options={'ordering': ['project_order'], 'verbose_name': 'Блок "О проекте"', 'verbose_name_plural': 'Блоки "О проекте"'},
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='block_id',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
