# Generated by Django 2.2.5 on 2023-07-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20230725_1342'),
        ('core', '0069_auto_20230725_1252'),
    ]

    operations = [
    ]
