# Generated by Django 2.2.5 on 2023-07-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_merge_20230725_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='is_project_info',
            field=models.BooleanField(default=True, editable=False, verbose_name='Блок раздела "О проекте"'),
        ),
    ]
