# Generated by Django 2.2.5 on 2023-07-25 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20230725_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='link',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='link_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заголовок ссылки'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='video',
            field=models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', '3gp', 'mpeg', 'qt', 'ogg', 'webm'])], verbose_name='Файл'),
        ),
    ]
