# Generated by Django 2.2.5 on 2023-07-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20230725_2105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instruction',
            new_name='SettingsModule',
        ),
    ]
