# Generated by Django 2.2.5 on 2023-07-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_auto_20230725_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingsmodule',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AlterField(
            model_name='settingsmodule',
            name='type',
            field=models.CharField(choices=[('INITIATIVE_SUBMISSION', 'Подать инициативу'), ('INITIATIVE_PROPOSAL', 'Предложить инициативу'), ('APPEAL_SUBMISSION', 'Подать обращение'), ('BANNER', 'Баннер'), ('PERSONAL_DATA_USAGE_POLICY', 'Политика использования персональных данных'), ('ABOUT_PROJECT', 'О проекте')], max_length=200, verbose_name='Тип инструкции'),
        ),
    ]
