# Generated by Django 2.2.5 on 2023-07-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_auto_20230726_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodule',
            name='type',
            field=models.CharField(choices=[('INITIATIVE_SUBMISSION', 'Подать инициативу'), ('INITIATIVE_PROPOSAL', 'Предложить инициативу'), ('APPEAL_SUBMISSION', 'Подать обращение'), ('BANNER', 'Баннер'), ('PERSONAL_DATA_USAGE_POLICY', 'Политика использования персональных данных'), ('MAIN_PAGE', 'Главная страница')], max_length=200, verbose_name='Тип настройки'),
        ),
    ]
