# Generated by Django 2.2.5 on 2023-07-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20230726_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodule',
            name='header',
            field=models.TextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='settingsmodule',
            name='type',
            field=models.CharField(choices=[('INITIATIVE_PROPOSAL', 'Предложить инициативу'), ('APPEAL_SUBMISSION', 'Подать обращение'), ('BANNER', 'Баннер'), ('PERSONAL_DATA_USAGE_POLICY', 'Политика использования персональных данных'), ('MAIN_PAGE', 'Главная страница'), ('USER_AGREEMENTS', 'Соглашения пользователей')], max_length=200, verbose_name='Тип настройки'),
        ),
    ]
