# Generated by Django 2.2.5 on 2023-07-26 10:15

from django.db import migrations, models

def save_about_us_data(apps, schema_editor):
    project_info = apps.get_model('core', 'ProjectInfo')
    active_citizen_module = apps.get_model('core', 'activecitizenmodule')
    about_project, _ = active_citizen_module.objects.get_or_create(name='about_project', defaults={'name': 'О проекте'})

    for i in project_info.objects.filter(is_project_info=True):
        i.site_module = about_project
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_auto_20230726_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование файла')),
                ('file', models.FileField(upload_to='import/modules/%Y/%m/%d', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Блок "О проекте"',
                'verbose_name_plural': 'Блоки "О проекте"',
            },
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='files_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание файлов'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='files',
            field=models.ManyToManyField(blank=True, to='core.BlockFile', verbose_name='Файлы'),
        ),
        migrations.RunPython(save_about_us_data),
    ]
