# Generated by Django 2.2.5 on 2023-07-26 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0087_auto_20230726_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='LkoLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Уровень ЛКО',
                'verbose_name_plural': 'Уровни ЛКО',
            },
        ),
        migrations.CreateModel(
            name='LkoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Тип ЛКО',
                'verbose_name_plural': 'Типы ЛКО',
            },
        ),
        migrations.AddField(
            model_name='departmentsubinfo',
            name='lko_level_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='core.LkoLevel', verbose_name='Уровень ЛКО'),
        ),
        migrations.AddField(
            model_name='departmentsubinfo',
            name='lko_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='core.LkoType', verbose_name='Тип ЛКО'),
        ),
    ]
