# Generated by Django 2.2.5 on 2023-07-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_merge_20230726_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectinfo',
            options={'ordering': ['project_order'], 'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
    ]
