# Generated by Django 2.2.5 on 2023-07-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_auto_20230726_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockfile',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы из модулей'},
        ),
    ]
