# Generated by Django 2.2.5 on 2023-07-27 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_auto_20230726_1704'),
        ('core', '0090_auto_20230726_1838'),
    ]

    operations = [
    ]
