# Generated by Django 2.2.5 on 2023-07-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_auto_20230727_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentsubinfo',
            options={'verbose_name': 'Дополнительная информация об организации', 'verbose_name_plural': 'Дополнительная информация об организациях'},
        ),
        migrations.AlterField(
            model_name='activecitizenmodule',
            name='name',
            field=models.CharField(choices=[('voting', 'Голосования'), ('initiatives', 'Инициативы'), ('appeals_pos', 'Обращения граждан'), ('ecology', 'Бонусная программа'), ('map_works', 'Карта ремонтных работ'), ('plans', 'Планы'), ('feedback', 'Обратная связь'), ('news', 'Новости'), ('about_project', 'О проекте'), ('new_module', 'Новый раздел')], max_length=100, verbose_name='Наименование'),
        ),
    ]
