# Generated by Django 2.2.5 on 2023-07-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_auto_20230728_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('IS_ACTIVE', 'Активно'), ('ARCHIVED', 'В архиве')], default='IS_ACTIVE', max_length=255, verbose_name='Статус'),
        ),
    ]
