# Generated by Django 2.2.5 on 2023-08-02 03:04

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_auto_20230731_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecitizenmodule',
            name='name',
            field=models.CharField(choices=[('voting', 'Голосования'), ('initiatives', 'Инициативы'), ('appeals_pos', 'Обращения граждан'), ('ecology', 'Бонусная программа'), ('map_works', 'Карта ремонтных работ'), ('plans', 'Планы'), ('feedback', 'Обратная связь'), ('news', 'Новости'), ('about_project', 'О проекте'), ('digital_consultant', 'Цифровой консультант'), ('new_module', 'Новый раздел')], max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.TextField(verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.TextField(unique=True, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='departmentsubinfo',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое название'),
        ),
        migrations.AlterField(
            model_name='departmentsubpermissions',
            name='appeals_categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='department_appeals_categories_permissions', to='appeals_pos.Category', verbose_name='Проблематика для модуля «Ваше мнение»'),
        ),
        migrations.AlterField(
            model_name='departmentsubpermissions',
            name='encouragement_categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='department_ecology_encouragement_categories_permission', to='ecology.GoodsNServicesItemCategory', verbose_name='Тематические категории для "Системы поощрения – Поощрения"'),
        ),
        migrations.AlterField(
            model_name='departmentsubpermissions',
            name='initiative_categories',
            field=models.ManyToManyField(blank=True, related_name='department_initiatives_categories_permissions', to='initiatives.InitiativeCategory', verbose_name='Категории для инициатив'),
        ),
        migrations.AlterField(
            model_name='departmentsubpermissions',
            name='map_works_categories',
            field=models.ManyToManyField(blank=True, related_name='department_map_works_categories_permissions', to='map_works.WorkCategory', verbose_name='Категории для карт'),
        ),
        migrations.AlterField(
            model_name='departmentsubpermissions',
            name='modules_permissions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MAP_WORKS', 'Карты'), ('PLANS', 'Планы'), ('VOTING', 'Голосования'), ('INITIATIVES', 'Инициативы'), ('APPEALS', 'Ваше мнение'), ('ENCOURAGEMENTS', 'Система поощрений – Поощрения'), ('SUGGESTIONS', 'Система поощрений – Предложения')], max_length=69, verbose_name='Настройки доступа к модулям ПО'),
        ),
        migrations.AlterField(
            model_name='departmentsubpermissions',
            name='plans_categories',
            field=models.ManyToManyField(blank=True, related_name='department_plans_categories_permissions', to='plans.Category', verbose_name='Категории для планов'),
        ),
        migrations.AlterField(
            model_name='departmentsubpermissions',
            name='suggestion_categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='department_ecology_suggestion_categories_permissions', to='ecology.EventCategory', verbose_name='Тематические категории для "Системы поощрения – Предложения"'),
        ),
        migrations.AlterField(
            model_name='departmentsubpermissions',
            name='voting_categories',
            field=models.ManyToManyField(blank=True, related_name='department_voting_categories_permissions', to='core.Category', verbose_name='Категории для голосований'),
        ),
        migrations.AlterField(
            model_name='operatorlkopermissions',
            name='initiatives_categories',
            field=models.ManyToManyField(blank=True, related_name='operator_initiatives_categories_permissions', to='initiatives.InitiativeCategory', verbose_name='Категории для инициатив'),
        ),
        migrations.AlterField(
            model_name='operatorlkopermissions',
            name='initiatives_localities',
            field=models.ManyToManyField(blank=True, related_name='operator_initiatives_localities_permissions', to='core.Locality', verbose_name='МО, по которым будут рассматриваться инициативы'),
        ),
        migrations.AlterField(
            model_name='operatorlkopermissions',
            name='map_works_categories',
            field=models.ManyToManyField(blank=True, related_name='operator_map_works_categories_permissions', to='map_works.WorkCategory', verbose_name='Категории для карт'),
        ),
        migrations.AlterField(
            model_name='operatorlkopermissions',
            name='map_works_localities',
            field=models.ManyToManyField(blank=True, related_name='operator_map_works_localities_permissions', to='core.Locality', verbose_name='Доступные муниципальные образования для карт'),
        ),
        migrations.AlterField(
            model_name='operatorlkopermissions',
            name='modules_permissions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MAP_WORKS', 'Карты'), ('PLANS', 'Планы'), ('VOTING', 'Голосования'), ('INITIATIVES', 'Инициативы'), ('APPEALS', 'Ваше мнение'), ('ENCOURAGEMENTS', 'Система поощрений – Поощрения'), ('SUGGESTIONS', 'Система поощрений – Предложения')], max_length=69, verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='operatorlkopermissions',
            name='plans_categories',
            field=models.ManyToManyField(blank=True, related_name='operator_plans_categories_permissions', to='plans.Category', verbose_name='Категории для планов'),
        ),
        migrations.AlterField(
            model_name='operatorlkopermissions',
            name='plans_localities',
            field=models.ManyToManyField(blank=True, related_name='operator_plans_localities_permissions', to='core.Locality', verbose_name='Доступные муниципальные образования для планов'),
        ),
        migrations.AlterField(
            model_name='operatorlkopermissions',
            name='voting_categories',
            field=models.ManyToManyField(blank=True, related_name='operator_voting_categories_permissions', to='core.Category', verbose_name='Категории для голосований'),
        ),
        migrations.AlterField(
            model_name='operatorlkopermissions',
            name='voting_municipalities',
            field=models.ManyToManyField(blank=True, related_name='operator_voting_municipalies_permissions', to='core.Locality', verbose_name='МО, по которым будут публиковаться голосования'),
        ),
    ]
