# Generated by Django 2.2.5 on 2023-08-02 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_auto_20230802_1325'),
        ('core', '0104_auto_20230802_1400'),
    ]

    operations = [
    ]
