# Generated by Django 2.2.5 on 2023-08-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals_pos', '0022_delete_appealfilinginstruction'),
        ('ecology', '0044_auto_20211122_1500'),
        ('core', '0107_auto_20230802_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorlkopermissions',
            name='appeals_categories',
            field=models.ManyToManyField(blank=True, related_name='operator_appeals_categories_permissions', to='appeals_pos.Category', verbose_name='Проблематика для модуля «Ваше мнение»'),
        ),
        migrations.AddField(
            model_name='operatorlkopermissions',
            name='appeals_localities',
            field=models.ManyToManyField(blank=True, related_name='operator_appeals_localities_permissions', to='core.Locality', verbose_name='Доступные муниципальные образования для модуля «Ваше мнение»'),
        ),
        migrations.AddField(
            model_name='operatorlkopermissions',
            name='encouragement_categories',
            field=models.ManyToManyField(blank=True, related_name='operator_encouragement_categories_permissions', to='ecology.GoodsNServicesItemCategory', verbose_name='Тематические категории Поощрений'),
        ),
        migrations.AddField(
            model_name='operatorlkopermissions',
            name='encouragement_localities',
            field=models.ManyToManyField(blank=True, related_name='operator_encouragement_localities_permissions', to='core.Locality', verbose_name='Доступные муниципальные образования Поощрений'),
        ),
        migrations.AddField(
            model_name='operatorlkopermissions',
            name='suggestion_categories',
            field=models.ManyToManyField(blank=True, related_name='operator_suggestion_categories_permissions', to='ecology.EventCategory', verbose_name='Тематические категории Предложений'),
        ),
        migrations.AddField(
            model_name='operatorlkopermissions',
            name='suggestion_localities',
            field=models.ManyToManyField(blank=True, related_name='operator_suggestion_localities_permissions', to='core.Locality', verbose_name='Доступные муниципальные образования Предложений'),
        ),
    ]
