# Generated by Django 2.2.5 on 2023-08-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_auto_20230802_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorlkopermissions',
            name='is_can_create',
        ),
        migrations.RemoveField(
            model_name='operatorlkopermissions',
            name='is_can_edit',
        ),
        migrations.RemoveField(
            model_name='operatorlkopermissions',
            name='is_can_view',
        ),
    ]
