# Generated by Django 2.2.5 on 2023-08-02 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_auto_20230802_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlkopermissions',
            name='sub_permissions',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_lko_permissions', to='core.SubPermissions', verbose_name='Дополнительные права роли админ ЛКО'),
        ),
        migrations.AlterField(
            model_name='operatorlkopermissions',
            name='user_sub_permissions',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_permissions', to='core.SubPermissions', verbose_name='Дополнительные права пользователя'),
        ),
    ]
