# Generated by Django 2.2.5 on 2023-08-02 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_auto_20230802_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinvite',
            name='admin_lko_permissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AdminLkoPermissions', verbose_name='Права роли админ ЛКО'),
        ),
        migrations.AddField(
            model_name='mailinvite',
            name='operator_permissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.OperatorLkoPermissions', verbose_name='Права роли оператора ЛКО'),
        ),
    ]
