# Generated by Django 2.2.5 on 2023-08-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_auto_20230802_2334'),
        ('core', '0109_auto_20230802_1830'),
    ]

    operations = [
    ]
