# Generated by Django 2.2.5 on 2023-08-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_merge_20230802_2339'),
        ('core', '0108_auto_20230802_1718'),
    ]

    operations = [
    ]
