# Generated by Django 2.2.5 on 2023-08-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_merge_20230802_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorlkopermissions',
            name='appeals_categories',
        ),
    ]
