# Generated by Django 2.2.5 on 2023-08-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0026_auto_20230802_1638'),
        ('core', '0112_remove_operatorlkopermissions_appeals_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorlkopermissions',
            name='appeals_categories',
            field=models.ManyToManyField(blank=True, related_name='operator_appeals_categories_permissions', to='feedback.Problematic', verbose_name='Проблематика для модуля «Ваше мнение»'),
        ),
    ]
