# Generated by Django 2.2.5 on 2023-08-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_auto_20230803_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationalmessages',
            name='header',
            field=models.TextField(blank=True, verbose_name='Название информационного сообщения'),
        ),
        migrations.AlterField(
            model_name='informationalmessages',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
