# Generated by Django 2.2.5 on 2023-08-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_auto_20230803_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlkopermissions',
            name='is_can_create',
        ),
        migrations.RemoveField(
            model_name='adminlkopermissions',
            name='is_can_edit',
        ),
        migrations.RemoveField(
            model_name='adminlkopermissions',
            name='is_can_view',
        ),
        migrations.AddField(
            model_name='adminlkopermissions',
            name='is_can_create_subdepartment',
            field=models.BooleanField(default=False, verbose_name='Доступность создания подведомственных организаций'),
        ),
        migrations.AddField(
            model_name='adminlkopermissions',
            name='is_can_edit_department',
            field=models.BooleanField(default=False, verbose_name='Доступность редактирования Организации'),
        ),
        migrations.AddField(
            model_name='adminlkopermissions',
            name='is_can_edit_subdepartment',
            field=models.BooleanField(default=False, verbose_name='Доступность редактирования Подведомственных организаций'),
        ),
    ]
