# Generated by Django 2.2.5 on 2023-08-04 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_auto_20230804_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlkopermissions',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='curatorpermissions',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='operatorlkopermissions',
            name='is_active',
        ),
    ]
