# Generated by Django 2.2.5 on 2023-08-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_auto_20230804_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality',
            options={'ordering': ['name'], 'verbose_name': 'Мунициипальное образование', 'verbose_name_plural': 'Муниципальные образования'},
        ),
        migrations.AlterField(
            model_name='curatorpermissions',
            name='initiatives_localities',
            field=models.ManyToManyField(blank=True, related_name='initiatives_localities', to='core.Locality', verbose_name='МО, по которым будут рассматриваться инициативы'),
        ),
        migrations.AlterField(
            model_name='curatorpermissions',
            name='initiatives_municipalities',
            field=models.ManyToManyField(blank=True, related_name='initiatives_municipalities', to='core.Locality', verbose_name='МО, по которым будут рассматриваться инициативы'),
        ),
        migrations.AlterField(
            model_name='curatorpermissions',
            name='map_works_localities',
            field=models.ManyToManyField(blank=True, related_name='map_works_localities', to='core.Locality', verbose_name='Доступные муниципальные образования для карт'),
        ),
        migrations.AlterField(
            model_name='curatorpermissions',
            name='map_works_municipalities',
            field=models.ManyToManyField(blank=True, related_name='map_works_municipalities', to='core.Locality', verbose_name='Доступные муниципальные образования для карт'),
        ),
        migrations.AlterField(
            model_name='curatorpermissions',
            name='plans_localities',
            field=models.ManyToManyField(blank=True, related_name='plans_localities', to='core.Locality', verbose_name='Доступные муниципальные образования для планов'),
        ),
        migrations.AlterField(
            model_name='curatorpermissions',
            name='plans_municipalities',
            field=models.ManyToManyField(blank=True, related_name='plans_municipalities', to='core.Locality', verbose_name='Доступные муниципальные образования для планов'),
        ),
        migrations.AlterField(
            model_name='curatorpermissions',
            name='voting_localities',
            field=models.ManyToManyField(blank=True, related_name='voting_localities', to='core.Locality', verbose_name='МО, по которым будут публиковаться голосования'),
        ),
        migrations.AlterField(
            model_name='curatorpermissions',
            name='voting_municipalities',
            field=models.ManyToManyField(blank=True, related_name='voting_municipalities', to='core.Locality', verbose_name='МО, по которым будут публиковаться голосования'),
        ),
        migrations.AlterField(
            model_name='operatorlkopermissions',
            name='initiatives_municipalities',
            field=models.ManyToManyField(blank=True, related_name='operator_initiatives_municipalities_permissions', to='core.Locality', verbose_name='МО, по которым будут рассматриваться инициативы'),
        ),
        migrations.AlterField(
            model_name='operatorlkopermissions',
            name='map_works_municipalities',
            field=models.ManyToManyField(blank=True, related_name='operator_map_works_municipalities_permissions', to='core.Locality', verbose_name='Доступные муниципальные образования для карт'),
        ),
        migrations.AlterField(
            model_name='operatorlkopermissions',
            name='plans_municipalities',
            field=models.ManyToManyField(blank=True, related_name='operator_plans_municipalities_permissions', to='core.Locality', verbose_name='Доступные муниципальные образования для планов'),
        ),
        migrations.AlterField(
            model_name='operatorlkopermissions',
            name='voting_localities',
            field=models.ManyToManyField(blank=True, related_name='operator_voting_categories_localities_permissions', to='core.Locality', verbose_name='МО, по которым будут публиковаться голосования'),
        ),
    ]
