# Generated by Django 2.2.5 on 2023-08-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_auto_20230804_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationalmessages',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Текст'),
        ),
    ]
