# Generated by Django 2.2.5 on 2023-08-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_user_deletion_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(verbose_name='Заголовок')),
                ('text', models.TextField(max_length=500, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Оповещение об удалении учётной записи',
                'verbose_name_plural': 'Оповещения об удалении учётной записи',
            },
        ),
    ]
