# Generated by Django 2.2.5 on 2023-08-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_user_snils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='snils',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='СНИЛС'),
        ),
    ]
