# Generated by Django 2.2.5 on 2023-10-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_auto_20230919_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecitizenmodule',
            name='name',
            field=models.CharField(choices=[('voting', 'Голосования'), ('initiatives', 'Инициативы'), ('appeals_pos', 'Обращения граждан'), ('ecology', 'Бонусная программа'), ('map_works', 'Карта ремонтных работ'), ('plans', 'Планы'), ('feedback', 'Обратная связь'), ('news', 'Новости'), ('about_project', 'О проекте'), ('digital_consultant', 'Цифровой консультант'), ('your_opinion', 'Ваше мнение'), ('new_module', 'Новый раздел')], max_length=100, verbose_name='Наименование'),
        ),
    ]
