# Generated by Django 2.2.5 on 2023-10-11 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_auto_20231011_1109'),
        ('core', '0135_user_email_appeals_notification'),
    ]

    operations = [
    ]
