# Generated by Django 2.2.5 on 2023-10-13 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_merge_20231011_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpageblock',
            options={'ordering': ['order'], 'verbose_name': 'Блок главной страницы', 'verbose_name_plural': 'Блоки главной страницы'},
        ),
        migrations.RemoveField(
            model_name='mainpageblock',
            name='block_id',
        ),
        migrations.RemoveField(
            model_name='mainpageblock',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mainpageblock',
            name='text',
        ),
        migrations.AddField(
            model_name='mainpageblock',
            name='name',
            field=models.CharField(blank=True, choices=[('INFORMATIONAL_MESSAGES', 'Информационные сообщения'), ('OFFICIALS', 'Должностные лица'), ('STATS', 'Статистика'), ('NEWS', 'Новости'), ('VOTING', 'Голосования')], max_length=30, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='mainpageblock',
            name='order',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Порядок'),
        ),
    ]
