# Generated by Django 2.2.5 on 2023-10-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_user_work_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinvite',
            name='work_phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Рабочий номер телефона'),
        ),
    ]
