# Generated by Django 2.2.5 on 2020-10-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecology", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecology.Event",
                verbose_name="Мероприятие",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user_ecology_level",
            field=models.TextField(
                blank=True,
                choices=[
                    ("UNDEFINED", "Неопределен"),
                    ("HIGH", "Высокий"),
                    ("MIDDLE", "Средний"),
                    ("LOW", "Низкий"),
                ],
                null=True,
                verbose_name="Операция с экостатусом",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="survey_reward",
            field=models.PositiveIntegerField(
                default=50, verbose_name="Награда за участие анкету"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="reward",
            field=models.PositiveIntegerField(
                verbose_name="Количество начисляемых бонусов за участие"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.TextField(
                choices=[
                    ("BALANCE", "Операция с балансом"),
                    ("ECOLOGY_LEVEL", "Операция с экостатусом пользователя"),
                ],
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user_balance_operation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ecology.UserBalanceOperation",
                verbose_name="Операция с балансом",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="state",
            field=models.TextField(
                choices=[
                    ("INITIAL", "Первоначальный"),
                    ("PARTICIPATE", "Принимает участие"),
                    ("SURVEY_SUSPEND", "Опрос отложен"),
                    ("SURVEY_COMPLETED", "Опрос пройден"),
                ],
                default="INITIAL",
                verbose_name="Состояние",
            ),
        ),
    ]
