# Generated by Django 2.2.5 on 2020-10-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecology", "0004_participationuserevent_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsnservicesitem",
            name="cost_money",
            field=models.PositiveIntegerField(default=0, verbose_name="Цена за деньги"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goodsnservicesitem",
            name="cost",
            field=models.PositiveIntegerField(verbose_name="Цена за бонусы"),
        ),
    ]
