# Generated by Django 2.2.5 on 2020-10-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecology", "0007_auto_20201011_1343"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpurchase",
            name="processed",
            field=models.BooleanField(default=False, verbose_name="Обработано"),
        ),
    ]
