# Generated by Django 2.2.5 on 2020-10-12 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ecology", "0008_userpurchase_processed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Наименование")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Анкета",
                "verbose_name_plural": "Анкеты",
            },
        ),
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                ("weight", models.FloatField(default=0.0, verbose_name="Вес")),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="ecology.Survey",
                        verbose_name="Анкета",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос анкеты",
                "verbose_name_plural": "Вопросы анкет",
            },
        ),
        migrations.CreateModel(
            name="SurveyQuestionAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                ("weight", models.FloatField(default=0.0, verbose_name="Вес")),
                ("group", models.TextField(blank=True, verbose_name="Группа")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="ecology.SurveyQuestion",
                        verbose_name="Вопрос анкеты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа на вопрос анкеты",
                "verbose_name_plural": "Варианты ответов на вопросы анкет",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.TextField(
                choices=[
                    ("BALANCE", "Изменен баланс"),
                    ("ECOLOGY_LEVEL", "Изменен экостатус"),
                    ("PARTICIPATE", "Принято участие в проекте"),
                    ("SURVEY_COMPLETED", "Заполнена анкета"),
                    ("EVENT_PARTICIPATION", "Принято участие в мероприятии"),
                    ("GOODSNSERVICES_PURCHASE", "Совершена покупка товара/услуги"),
                ],
                verbose_name="Тип",
            ),
        ),
        migrations.CreateModel(
            name="UserSurvey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecology.SurveyQuestionAnswer",
                        verbose_name="Вариант ответа",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecology.SurveyQuestion",
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecology.Survey",
                        verbose_name="Анкета",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ пользователя",
                "verbose_name_plural": "Ответы пользователей",
            },
        ),
        migrations.AddIndex(
            model_name="usersurvey",
            index=models.Index(
                fields=["user", "survey"], name="ecology_use_user_id_b12168_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersurvey",
            index=models.Index(
                fields=["user", "survey", "question"],
                name="ecology_use_user_id_5317c0_idx",
            ),
        ),
    ]
