# Generated by Django 2.2.5 on 2020-10-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecology", "0009_auto_20201012_1043"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyquestion",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
        migrations.AddField(
            model_name="surveyquestionanswer",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
    ]
