# Generated by Django 2.2.5 on 2020-10-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecology", "0011_auto_20201012_1450"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyquestionanswer",
            name="group",
            field=models.TextField(blank=True, null=True, verbose_name="Группа"),
        ),
    ]
