# Generated by Django 2.2.5 on 2021-09-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecology", "0014_usersurvey_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="expiry_publication_date",
            field=models.DateField(null=True, verbose_name="Дата конца публикации"),
        ),
        migrations.AddField(
            model_name="event",
            name="start_publication_date",
            field=models.DateField(null=True, verbose_name="Дата начала публикации"),
        ),
    ]
