# Generated by Django 2.2.5 on 2021-09-10 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecology", "0019_auto_20210910_0832"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="maximun_participants",
            new_name="maximum_participants",
        ),
    ]
