# Generated by Django 2.2.5 on 2021-09-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecology", "0020_auto_20210910_0833"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participationuserevent",
            options={
                "verbose_name": "Участие пользователя в мероприятии",
                "verbose_name_plural": "Участие пользователей в мероприятиях",
            },
        ),
        migrations.RemoveField(
            model_name="participationuserevent",
            name="confirmed",
        ),
        migrations.AddField(
            model_name="participationuserevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_CONFIRMED", "Не подтверждено"),
                    ("CONFIRMED", "Подтверждено"),
                    ("DECLINED", "Отклонено"),
                ],
                default="NOT_CONFIRMED",
                max_length=30,
                verbose_name="Статус участия",
            ),
        ),
        migrations.AddIndex(
            model_name="participationuserevent",
            index=models.Index(
                fields=["participant", "event"], name="ecology_par_partici_167eb8_idx"
            ),
        ),
    ]
