# Generated by Django 2.2.5 on 2021-09-15 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecology", "0024_event_organization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "verbose_name": "Предложение",
                "verbose_name_plural": "Предложения",
            },
        ),
        migrations.AlterModelOptions(
            name="eventcategory",
            options={
                "verbose_name": "Категория предложения",
                "verbose_name_plural": "Категории предложений",
            },
        ),
        migrations.AlterModelOptions(
            name="goodsnservicesitemcategory",
            options={
                "verbose_name": "Категория поощрений",
                "verbose_name_plural": "Категории поощрений",
            },
        ),
    ]
