# Generated by Django 2.2.5 on 2021-09-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecology", "0027_auto_20210916_1527"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="module_information",
            field=models.TextField(
                max_length=500,
                null=True,
                verbose_name="Описание программы «Система поощрений»",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="status_instruction",
            field=models.TextField(
                max_length=500,
                null=True,
                verbose_name="Инструкция для повышения статуса",
            ),
        ),
    ]
