# Generated by Django 2.2.5 on 2021-09-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecology", "0029_participationuserevent_confirmation_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyquestion",
            name="weight",
        ),
        migrations.RemoveField(
            model_name="surveyquestionanswer",
            name="weight",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="ecology_level",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="ecology_level_percentage",
        ),
        migrations.AddField(
            model_name="settings",
            name="max_beginner_bonuses",
            field=models.PositiveIntegerField(
                default=299,
                verbose_name='Максимальное количество бонусов для статуса "Новичок"',
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="max_city_expert_bonuses",
            field=models.PositiveIntegerField(
                default=2999,
                verbose_name='Максимальное количество бонусов для статуса "Городской эксперт"',
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="max_dweller_bonuses",
            field=models.PositiveIntegerField(
                default=999,
                verbose_name='Максимальное количество бонусов для статуса "Житель"',
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="min_active_citizen_bonuses",
            field=models.PositiveIntegerField(
                default=3000,
                verbose_name='Минимальное количество бонусов для статуса "Активный гражданин"',
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="min_beginner_bonuses",
            field=models.PositiveIntegerField(
                default=0,
                verbose_name='Минимальное количество бонусов для статуса "Новичок"',
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="min_city_expert_bonuses",
            field=models.PositiveIntegerField(
                default=1000,
                verbose_name='Минимальное количество бонусов для статуса "Городской эксперт"',
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="min_dweller_bonuses",
            field=models.PositiveIntegerField(
                default=300,
                verbose_name='Минимальное количество бонусов для статуса "Житель"',
            ),
        ),
    ]
