# Generated by Django 2.2.5 on 2021-09-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_auto_20210915_1052"),
        ("ecology", "0031_auto_20210921_1627"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsnservicesitem",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Organization",
                verbose_name="Организация",
            ),
        ),
    ]
