# Generated by Django 2.2.5 on 2021-10-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecology", "0034_auto_20210930_1009"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsnservicesitem",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="goodsnservicesitem",
            name="maximum_purchasers",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Ограничение на количество пользователей, которые могут получить поощрение",
            ),
        ),
        migrations.AddField(
            model_name="goodsnservicesitem",
            name="multiple_purchase",
            field=models.BooleanField(
                default=False,
                verbose_name="Многократное приобретение поощрения пользователем",
            ),
        ),
    ]
