# Generated by Django 2.2.5 on 2021-10-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecology", "0037_remove_goodsnservicesitemcategory_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="coordinates",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Координаты"
            ),
        ),
        migrations.AddField(
            model_name="goodsnservicesitem",
            name="coordinates",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Координаты"
            ),
        ),
    ]
