# Generated by Django 2.2.5 on 2021-10-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecology", "0041_auto_20211026_1705"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"verbose_name": "Операция", "verbose_name_plural": "Операции"},
        ),
        migrations.RemoveField(
            model_name="event",
            name="image",
        ),
        migrations.RemoveField(
            model_name="event",
            name="is_opened",
        ),
        migrations.RemoveField(
            model_name="goodsnservicesitem",
            name="image",
        ),
        migrations.RemoveField(
            model_name="userbalanceoperation",
            name="participation",
        ),
        migrations.RemoveField(
            model_name="userbalanceoperation",
            name="purchase",
        ),
        migrations.AddField(
            model_name="goodsnservicesitem",
            name="return_possibility",
            field=models.BooleanField(
                default=False, verbose_name="Возможность возврата"
            ),
        ),
        migrations.AlterField(
            model_name="goodsnservicesitem",
            name="contacts",
            field=models.TextField(
                verbose_name="Описание контактных данных Партнера для получения Поощрения"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.TextField(
                choices=[
                    ("PARTICIPATE", "Принято участие в проекте"),
                    ("SURVEY_COMPLETED", "Заполнена анкета"),
                    ("EVENT_PARTICIPATION", "Принято участие в мероприятии"),
                    ("DECLINE_EVENT_PARTICIPATION", "Отклонено участие в предложении"),
                    ("GOODSNSERVICES_PURCHASE", "Совершена покупка поощрения"),
                    ("RETURN_GOODSNSERVICES_PURCHASE", "Произведен возврат поощрения"),
                    ("ADDING_INITIATIVE", "Предложена инициатива"),
                    ("APPROVE_INITIATIVE", "Поддержана инициатива"),
                    ("VOTING_PARTICIPATION", "Принято участие в голосовании"),
                ],
                verbose_name="Тип",
            ),
        ),
    ]
