# Generated by Django 2.2.5 on 2021-11-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecology", "0043_auto_20211028_1041"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Категория предложения",
                "verbose_name_plural": "Категории предложений",
            },
        ),
        migrations.AlterModelOptions(
            name="goodsnservicesitemcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Категория поощрений",
                "verbose_name_plural": "Категории поощрений",
            },
        ),
    ]
