# Generated by Django 2.2.5 on 2023-09-19 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecology', '0044_auto_20211122_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='earned_bonuses',
            field=models.IntegerField(default=0, verbose_name='Количество всех заработанных бонусов'),
        ),
    ]
