# Generated by Django 2.2.5 on 2023-10-17 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_auto_20231013_1146'),
        ('ecology', '0047_auto_20231016_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='display_localities',
            field=models.ManyToManyField(blank=True, related_name='display_localities_event', to='core.Locality', verbose_name='Муниципальные образования для отображения'),
        ),
        migrations.AddField(
            model_name='goodsnservicesitem',
            name='display_localities',
            field=models.ManyToManyField(blank=True, related_name='display_localities_goods_n_services_item', to='core.Locality', verbose_name='Муниципальные образования для отображения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Locality', verbose_name='Муниципальное образование проведения'),
        ),
        migrations.AlterField(
            model_name='goodsnservicesitem',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Locality', verbose_name='Муниципальное образование проведения'),
        ),
    ]
