# coding: utf-8

"""
    Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference

    <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v12/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>   # noqa: E501

    The version of the OpenAPI document: v12
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from yahoo_display_test.configuration import Configuration


class RecommendationServiceDailyBudgetOverCampaign(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'recommendation_id': 'int',
        'campaign_id': 'int',
        'campaign_name': 'str',
        'current_budget': 'int'
    }

    attribute_map = {
        'recommendation_id': 'recommendationId',
        'campaign_id': 'campaignId',
        'campaign_name': 'campaignName',
        'current_budget': 'currentBudget'
    }

    def __init__(self, recommendation_id=None, campaign_id=None, campaign_name=None, current_budget=None, local_vars_configuration=None):  # noqa: E501
        """RecommendationServiceDailyBudgetOverCampaign - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._recommendation_id = None
        self._campaign_id = None
        self._campaign_name = None
        self._current_budget = None
        self.discriminator = None

        self.recommendation_id = recommendation_id
        self.campaign_id = campaign_id
        self.campaign_name = campaign_name
        self.current_budget = current_budget

    @property
    def recommendation_id(self):
        """Gets the recommendation_id of this RecommendationServiceDailyBudgetOverCampaign.  # noqa: E501

        <div lang=\"ja\"> 最適化提案IDです。<br> optimizationScoreLiftがnullでない場合は、1つのキャンペーンに関する提案に共通の最適化提案IDが割り当てられます。 </div> <div lang=\"en\"> Recommendation ID.<br> When optimizationScoreLift isn't null, the system will assign a common recommendation ID to the suggestion for the campaign. </div>   # noqa: E501

        :return: The recommendation_id of this RecommendationServiceDailyBudgetOverCampaign.  # noqa: E501
        :rtype: int
        """
        return self._recommendation_id

    @recommendation_id.setter
    def recommendation_id(self, recommendation_id):
        """Sets the recommendation_id of this RecommendationServiceDailyBudgetOverCampaign.

        <div lang=\"ja\"> 最適化提案IDです。<br> optimizationScoreLiftがnullでない場合は、1つのキャンペーンに関する提案に共通の最適化提案IDが割り当てられます。 </div> <div lang=\"en\"> Recommendation ID.<br> When optimizationScoreLift isn't null, the system will assign a common recommendation ID to the suggestion for the campaign. </div>   # noqa: E501

        :param recommendation_id: The recommendation_id of this RecommendationServiceDailyBudgetOverCampaign.  # noqa: E501
        :type: int
        """

        self._recommendation_id = recommendation_id

    @property
    def campaign_id(self):
        """Gets the campaign_id of this RecommendationServiceDailyBudgetOverCampaign.  # noqa: E501

        <div lang=\"ja\"> キャンペーンIDです。<br> </div> <div lang=\"en\"> Campaign ID.<br> </div>   # noqa: E501

        :return: The campaign_id of this RecommendationServiceDailyBudgetOverCampaign.  # noqa: E501
        :rtype: int
        """
        return self._campaign_id

    @campaign_id.setter
    def campaign_id(self, campaign_id):
        """Sets the campaign_id of this RecommendationServiceDailyBudgetOverCampaign.

        <div lang=\"ja\"> キャンペーンIDです。<br> </div> <div lang=\"en\"> Campaign ID.<br> </div>   # noqa: E501

        :param campaign_id: The campaign_id of this RecommendationServiceDailyBudgetOverCampaign.  # noqa: E501
        :type: int
        """

        self._campaign_id = campaign_id

    @property
    def campaign_name(self):
        """Gets the campaign_name of this RecommendationServiceDailyBudgetOverCampaign.  # noqa: E501

        <div lang=\"ja\"> キャンペーン名です。<br> </div> <div lang=\"en\"> Campaign name.<br> </div>   # noqa: E501

        :return: The campaign_name of this RecommendationServiceDailyBudgetOverCampaign.  # noqa: E501
        :rtype: str
        """
        return self._campaign_name

    @campaign_name.setter
    def campaign_name(self, campaign_name):
        """Sets the campaign_name of this RecommendationServiceDailyBudgetOverCampaign.

        <div lang=\"ja\"> キャンペーン名です。<br> </div> <div lang=\"en\"> Campaign name.<br> </div>   # noqa: E501

        :param campaign_name: The campaign_name of this RecommendationServiceDailyBudgetOverCampaign.  # noqa: E501
        :type: str
        """

        self._campaign_name = campaign_name

    @property
    def current_budget(self):
        """Gets the current_budget of this RecommendationServiceDailyBudgetOverCampaign.  # noqa: E501

        <div lang=\"ja\"> 現在のキャンペーン予算です。 </div> <div lang=\"en\"> Current campaign budget. </div>   # noqa: E501

        :return: The current_budget of this RecommendationServiceDailyBudgetOverCampaign.  # noqa: E501
        :rtype: int
        """
        return self._current_budget

    @current_budget.setter
    def current_budget(self, current_budget):
        """Sets the current_budget of this RecommendationServiceDailyBudgetOverCampaign.

        <div lang=\"ja\"> 現在のキャンペーン予算です。 </div> <div lang=\"en\"> Current campaign budget. </div>   # noqa: E501

        :param current_budget: The current_budget of this RecommendationServiceDailyBudgetOverCampaign.  # noqa: E501
        :type: int
        """

        self._current_budget = current_budget

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RecommendationServiceDailyBudgetOverCampaign):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RecommendationServiceDailyBudgetOverCampaign):
            return True

        return self.to_dict() != other.to_dict()
