# Generated by Django 2.2.5 on 2020-06-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20200623_1317"),
        ("initiatives", "0003_initiativeacceptingsettings_category"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="initiativeacceptingsettings",
            unique_together={
                ("locality", "category"),
            },
        ),
    ]
