# Generated by Django 2.2.5 on 2020-06-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0005_auto_20200625_1336"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiativefile",
            name="name",
            field=models.TextField(default="", verbose_name="Имя файла"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="initiative",
            name="files",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="initiatives.InitiativeFile",
                verbose_name="Файлы",
            ),
        ),
    ]
