# Generated by Django 2.2.5 on 2020-07-27 09:13

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0013_auto_20200710_1523"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initiative",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("PREMODERATION", "Модерирование"),
                    ("REJECTED_PREMODERATION", "Отклонена по итогам подерирования"),
                    ("CHANGES_APPROVAL", "Согласование изменений"),
                    ("MODERATION", "Экспертная оценка"),
                    ("REJECTED", "Отклонена"),
                    ("VOTES_COLLECTION", "Сбор голосов"),
                    ("REJECTED_VOTES_THRESHOLD", "Порог голосования не пройден"),
                    ("CONSIDERATION", "На рассмотрении"),
                    ("IN_PROGRESS", "Принято решение"),
                    ("ACCOMPLISHED", "Реализовано"),
                ],
                max_length=50,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="initiativestatechange",
            name="new_state",
            field=models.TextField(
                choices=[
                    ("PREMODERATION", "Модерирование"),
                    ("REJECTED_PREMODERATION", "Отклонена по итогам подерирования"),
                    ("CHANGES_APPROVAL", "Согласование изменений"),
                    ("MODERATION", "Экспертная оценка"),
                    ("REJECTED", "Отклонена"),
                    ("VOTES_COLLECTION", "Сбор голосов"),
                    ("REJECTED_VOTES_THRESHOLD", "Порог голосования не пройден"),
                    ("CONSIDERATION", "На рассмотрении"),
                    ("IN_PROGRESS", "Принято решение"),
                    ("ACCOMPLISHED", "Реализовано"),
                ],
                verbose_name="Новый статус",
            ),
        ),
    ]
