{
    "JSONIFY_PRETTYPRINT_REGULAR": false,
    "code": "aeolus/ok",
    "data": {
        "baseConf": {
            "appId": 5,
            "confidentiality": "",
            "connectionMode": 0,
            "demoUrl": "",
            "descr": null,
            "groupId": 0,
            "groupName": null,
            "groupType": 0,
            "id": 928,
            "isAuthEnabled": 1,
            "isIntelligentSyncEnable": 1,
            "name": "dm_ad_cast_adpos_after_uv_all_dws（后贴续播报表）",
            "ownerEmailPrefix": "maijiaming",
            "parentId": 0,
            "productName": "",
            "syncMode": 0,
            "thirdPartyConf": null,
            "type": 22
        },
        "dagTagConf": {
            "dimTbNodes": []
        },
        "dimMetList": [
            {
                "calcType": null,
                "dataFormat": null,
                "dataTypeName": "date",
                "defaultDataTypeName": "date",
                "descr": "p_date",
                "dimMetCategoryId": null,
                "dimMetCategoryType": null,
                "dimMetMixOrder": 0,
                "dimMetOrder": 0,
                "dimMetThirdPartyConf": null,
                "dimMetVariety": 1,
                "editable": 0,
                "errCode": "ok",
                "expr": "p_date",
                "exprAsDim": null,
                "fieldList": "[\"p_date\"]",
                "fullExpr": "p_date",
                "geoInfo": null,
                "groupType": 0,
                "hitFilterRuleList": [],
                "id": 1452735,
                "isDeletedField": 0,
                "isPartitionField": 1,
                "lodType": null,
                "mapType": 0,
                "name": "p_date",
                "operationCode": 0,
                "ownerEmailPrefix": "maijiaming",
                "paramIdList": [],
                "showExpr": 1,
                "visible": 1
            },
            {
                "calcType": null,
                "dataFormat": null,
                "dataTypeName": "int",
                "defaultDataTypeName": "int",
                "descr": "请求续播",
                "dimMetCategoryId": null,
                "dimMetCategoryType": null,
                "dimMetMixOrder": 5,
                "dimMetOrder": 0,
                "dimMetThirdPartyConf": null,
                "dimMetVariety": 2,
                "editable": 1,
                "errCode": "ok",
                "expr": "sn_1_succ_pv",
                "exprAsDim": null,
                "fieldList": "[\"sn_1_succ_pv\"]",
                "fullExpr": "sn_1_succ_pv",
                "groupType": 0,
                "hitFilterRuleList": [],
                "id": 1452744,
                "isDeletedField": 0,
                "isPartitionField": 0,
                "lodType": null,
                "mapType": 1,
                "name": "sn_1_succ_pv",
                "operationCode": 0,
                "ownerEmailPrefix": "maijiaming",
                "paramIdList": [],
                "showExpr": 1,
                "visible": 1
            },
            {
                "calcType": null,
                "dataFormat": null,
                "dataTypeName": "date",
                "defaultDataTypeName": "date",
                "descr": "",
                "dimMetCategoryId": null,
                "dimMetCategoryType": null,
                "dimMetMixOrder": 18,
                "dimMetOrder": 1,
                "dimMetThirdPartyConf": null,
                "dimMetVariety": 2,
                "editable": 1,
                "errCode": "ok",
                "expr": "to_date(p_date_lebo_data_dm_ad_cast_adpos_after_uv,'yyyymmdd')",
                "exprAsDim": null,
                "fieldList": "[\"p_date_lebo_data_dm_ad_cast_adpos_after_uv\"]",
                "fullExpr": "to_date(p_date_lebo_data_dm_ad_cast_adpos_after_uv,'yyyymmdd')",
                "groupType": 0,
                "hitFilterRuleList": [],
                "id": 1452743,
                "isDeletedField": 0,
                "isPartitionField": 0,
                "lodType": null,
                "mapType": 0,
                "name": "t_date",
                "operationCode": 0,
                "ownerEmailPrefix": "maijiaming",
                "paramIdList": [],
                "showExpr": 1,
                "visible": 1
            },
            {
                "calcType": null,
                "dataFormat": null,
                "dataTypeName": "int",
                "defaultDataTypeName": "int",
                "descr": "请求续播",
                "dimMetCategoryId": null,
                "dimMetCategoryType": null,
                "dimMetMixOrder": 6,
                "dimMetOrder": 1,
                "dimMetThirdPartyConf": null,
                "dimMetVariety": 2,
                "editable": 1,
                "errCode": "ok",
                "expr": "sn_1_succ_uv",
                "exprAsDim": null,
                "fieldList": "[\"sn_1_succ_uv\"]",
                "fullExpr": "sn_1_succ_uv",
                "groupType": 0,
                "hitFilterRuleList": [],
                "id": 1452745,
                "isDeletedField": 0,
                "isPartitionField": 0,
                "lodType": null,
                "mapType": 1,
                "name": "sn_1_succ_uv",
                "operationCode": 0,
                "ownerEmailPrefix": "maijiaming",
                "paramIdList": [],
                "showExpr": 1,
                "visible": 1
            },
            {
                "calcType": null,
                "dataFormat": null,
                "dataTypeName": "string",
                "defaultDataTypeName": "string",
                "descr": "",
                "dimMetCategoryId": null,
                "dimMetCategoryType": null,
                "dimMetMixOrder": 22,
                "dimMetOrder": 2,
                "dimMetThirdPartyConf": null,
                "dimMetVariety": 2,
                "editable": 1,
                "errCode": "ok",
                "expr": "tag",
                "exprAsDim": null,
                "fieldList": "[\"tag\"]",
                "fullExpr": "tag",
                "groupType": 0,
                "hitFilterRuleList": [],
                "id": 1453412,
                "isDeletedField": 0,
                "isPartitionField": 0,
                "lodType": null,
                "mapType": 0,
                "name": "tag",
                "operationCode": 0,
                "ownerEmailPrefix": "maijiaming",
                "paramIdList": [],
                "showExpr": 1,
                "visible": 1
            },
            {
                "calcType": null,
                "dataFormat": null,
                "dataTypeName": "int",
                "defaultDataTypeName": "int",
                "descr": "可续播数量",
                "dimMetCategoryId": null,
                "dimMetCategoryType": null,
                "dimMetMixOrder": 7,
                "dimMetOrder": 2,
                "dimMetThirdPartyConf": null,
                "dimMetVariety": 2,
                "editable": 1,
                "errCode": "ok",
                "expr": "sn_2_succ_pv",
                "exprAsDim": null,
                "fieldList": "[\"sn_2_succ_pv\"]",
                "fullExpr": "sn_2_succ_pv",
                "groupType": 0,
                "hitFilterRuleList": [],
                "id": 1452746,
                "isDeletedField": 0,
                "isPartitionField": 0,
                "lodType": null,
                "mapType": 1,
                "name": "sn_2_succ_pv",
                "operationCode": 0,
                "ownerEmailPrefix": "maijiaming",
                "paramIdList": [],
                "showExpr": 1,
                "visible": 1
            },
            {
                "calcType": null,
                "dataFormat": null,
                "dataTypeName": "int",
                "defaultDataTypeName": "int",
                "descr": "可续播数量",
                "dimMetCategoryId": null,
                "dimMetCategoryType": null,
                "dimMetMixOrder": 8,
                "dimMetOrder": 3,
                "dimMetThirdPartyConf": null,
                "dimMetVariety": 2,
                "editable": 1,
                "errCode": "ok",
                "expr": "sn_2_succ_uv",
                "exprAsDim": null,
                "fieldList": "[\"sn_2_succ_uv\"]",
                "fullExpr": "sn_2_succ_uv",
                "groupType": 0,
                "hitFilterRuleList": [],
                "id": 1452747,
                "isDeletedField": 0,
                "isPartitionField": 0,
                "lodType": null,
                "mapType": 1,
                "name": "sn_2_succ_uv",
                "operationCode": 0,
                "ownerEmailPrefix": "maijiaming",
                "paramIdList": [],
                "showExpr": 1,
                "visible": 1
            },
            {
                "calcType": null,
                "dataFormat": null,
                "dataTypeName": "int",
                "defaultDataTypeName": "int",
                "descr": "请求拉起数量",
                "dimMetCategoryId": null,
                "dimMetCategoryType": null,
                "dimMetMixOrder": 9,
                "dimMetOrder": 4,
                "dimMetThirdPartyConf": null,
                "dimMetVariety": 2,
                "editable": 1,
                "errCode": "ok",
                "expr": "sn_3_succ_pv",
                "exprAsDim": null,
                "fieldList": "[\"sn_3_succ_pv\"]",
                "fullExpr": "sn_3_succ_pv",
                "groupType": 0,
                "hitFilterRuleList": [],
                "id": 1452748,
                "isDeletedField": 0,
                "isPartitionField": 0,
                "lodType": null,
                "mapType": 1,
                "name": "sn_3_succ_pv",
                "operationCode": 0,
                "ownerEmailPrefix": "maijiaming",
                "paramIdList": [],
                "showExpr": 1,
                "visible": 1
            },
            {
                "calcType": null,
                "dataFormat": null,
                "dataTypeName": "int",
                "defaultDataTypeName": "int",
                "descr": "请求拉起数量",
                "dimMetCategoryId": null,
                "dimMetCategoryType": null,
                "dimMetMixOrder": 10,
                "dimMetOrder": 5,
                "dimMetThirdPartyConf": null,
                "dimMetVariety": 2,
                "editable": 1,
                "errCode": "ok",
                "expr": "sn_3_succ_uv",
                "exprAsDim": null,
                "fieldList": "[\"sn_3_succ_uv\"]",
                "fullExpr": "sn_3_succ_uv",
                "groupType": 0,
                "hitFilterRuleList": [],
                "id": 1452749,
                "isDeletedField": 0,
                "isPartitionField": 0,
                "lodType": null,
                "mapType": 1,
                "name": "sn_3_succ_uv",
                "operationCode": 0,
                "ownerEmailPrefix": "maijiaming",
                "paramIdList": [],
                "showExpr": 1,
                "visible": 1
            },
            {
                "calcType": null,
                "dataFormat": null,
                "dataTypeName": "int",
                "defaultDataTypeName": "int",
                "descr": "实际拉起",
                "dimMetCategoryId": null,
                "dimMetCategoryType": null,
                "dimMetMixOrder": 11,
                "dimMetOrder": 6,
                "dimMetThirdPartyConf": null,
                "dimMetVariety": 2,
                "editable": 1,
                "errCode": "ok",
                "expr": "sn_100_succ_pv",
                "exprAsDim": null,
                "fieldList": "[\"sn_100_succ_pv\"]",
                "fullExpr": "sn_100_succ_pv",
                "groupType": 0,
                "hitFilterRuleList": [],
                "id": 1452750,
                "isDeletedField": 0,
                "isPartitionField": 0,
                "lodType": null,
                "mapType": 1,
                "name": "sn_100_succ_pv",
                "operationCode": 0,
                "ownerEmailPrefix": "maijiaming",
                "paramIdList": [],
                "showExpr": 1,
                "visible": 1
            },
            {
                "calcType": null,
                "dataFormat": null,
                "dataTypeName": "int",
                "defaultDataTypeName": "int",
                "descr": "实际拉起",
                "dimMetCategoryId": null,
                "dimMetCategoryType": null,
                "dimMetMixOrder": 12,
                "dimMetOrder": 7,
                "dimMetThirdPartyConf": null,
                "dimMetVariety": 2,
                "editable": 1,
                "errCode": "ok",
                "expr": "sn_100_succ_uv",
                "exprAsDim": null,
                "fieldList": "[\"sn_100_succ_uv\"]",
                "fullExpr": "sn_100_succ_uv",
                "groupType": 0,
                "hitFilterRuleList": [],
                "id": 1452751,
                "isDeletedField": 0,
                "isPartitionField": 0,
                "lodType": null,
                "mapType": 1,
                "name": "sn_100_succ_uv",
                "operationCode": 0,
                "ownerEmailPrefix": "maijiaming",
                "paramIdList": [],
                "showExpr": 1,
                "visible": 1
            },
            {
                "calcType": null,
                "dataFormat": null,
                "dataTypeName": "int",
                "defaultDataTypeName": "int",
                "descr": "",
                "dimMetCategoryId": null,
                "dimMetCategoryType": null,
                "dimMetMixOrder": 13,
                "dimMetOrder": 8,
                "dimMetThirdPartyConf": null,
                "dimMetVariety": 2,
                "editable": 1,
                "errCode": "ok",
                "expr": "push_pv",
                "exprAsDim": null,
                "fieldList": "[\"push_pv\"]",
                "fullExpr": "push_pv",
                "groupType": 0,
                "hitFilterRuleList": [],
                "id": 1452752,
                "isDeletedField": 0,
                "isPartitionField": 0,
                "lodType": null,
                "mapType": 1,
                "name": "push_pv",
                "operationCode": 0,
                "ownerEmailPrefix": "maijiaming",
                "paramIdList": [],
                "showExpr": 1,
                "visible": 1
            },
            {
                "calcType": null,
                "dataFormat": null,
                "dataTypeName": "int",
                "defaultDataTypeName": "int",
                "descr": "",
                "dimMetCategoryId": null,
                "dimMetCategoryType": null,
                "dimMetMixOrder": 14,
                "dimMetOrder": 9,
                "dimMetThirdPartyConf": null,
                "dimMetVariety": 2,
                "editable": 1,
                "errCode": "ok",
                "expr": "receiver_uid",
                "exprAsDim": null,
                "fieldList": "[\"receiver_uid\"]",
                "fullExpr": "receiver_uid",
                "groupType": 0,
                "hitFilterRuleList": [],
                "id": 1452753,
                "isDeletedField": 0,
                "isPartitionField": 0,
                "lodType": null,
                "mapType": 1,
                "name": "receiver_uid",
                "operationCode": 0,
                "ownerEmailPrefix": "maijiaming",
                "paramIdList": [],
                "showExpr": 1,
                "visible": 1
            },
            {
                "calcType": null,
                "dataFormat": null,
                "dataSetId": 928,
                "dimIdList": [
                    1452736,
                    1452738,
                    1452740,
                    1452741
                ],
                "dimList": [
                    {
                        "calcType": null,
                        "dataFormat": null,
                        "dataTypeName": "string",
                        "defaultDataTypeName": "string",
                        "descr": "",
                        "dimMetCategoryId": null,
                        "dimMetCategoryType": null,
                        "dimMetMixOrder": 1,
                        "dimMetOrder": 4,
                        "dimMetThirdPartyConf": null,
                        "dimMetVariety": 2,
                        "editable": 1,
                        "errCode": "ok",
                        "expr": "client_appid",
                        "exprAsDim": null,
                        "fieldList": "[\"client_appid\"]",
                        "fullExpr": "client_appid",
                        "groupType": 0,
                        "hitFilterRuleList": [],
                        "id": 1452736,
                        "isDeletedField": 0,
                        "isPartitionField": 0,
                        "lodType": null,
                        "mapType": 0,
                        "name": "client_appid",
                        "operationCode": 0,
                        "ownerEmailPrefix": "maijiaming",
                        "paramIdList": [],
                        "showExpr": 1,
                        "visible": 1
                    },
                    {
                        "calcType": null,
                        "dataFormat": null,
                        "dataTypeName": "string",
                        "defaultDataTypeName": "string",
                        "descr": "",
                        "dimMetCategoryId": null,
                        "dimMetCategoryType": null,
                        "dimMetMixOrder": 3,
                        "dimMetOrder": 5,
                        "dimMetThirdPartyConf": null,
                        "dimMetVariety": 2,
                        "editable": 1,
                        "errCode": "ok",
                        "expr": "receiver_appid",
                        "exprAsDim": null,
                        "fieldList": "[\"receiver_appid\"]",
                        "fullExpr": "receiver_appid",
                        "groupType": 0,
                        "hitFilterRuleList": [],
                        "id": 1452738,
                        "isDeletedField": 0,
                        "isPartitionField": 0,
                        "lodType": null,
                        "mapType": 0,
                        "name": "receiver_appid",
                        "operationCode": 0,
                        "ownerEmailPrefix": "maijiaming",
                        "paramIdList": [],
                        "showExpr": 1,
                        "visible": 1
                    },
                    {
                        "calcType": null,
                        "dataFormat": null,
                        "dataTypeName": "string",
                        "defaultDataTypeName": "string",
                        "descr": "",
                        "dimMetCategoryId": null,
                        "dimMetCategoryType": null,
                        "dimMetMixOrder": 15,
                        "dimMetOrder": 6,
                        "dimMetThirdPartyConf": null,
                        "dimMetVariety": 2,
                        "editable": 1,
                        "errCode": "ok",
                        "expr": "client_appid_name",
                        "exprAsDim": null,
                        "fieldList": "[\"client_appid_name\"]",
                        "fullExpr": "client_appid_name",
                        "groupType": 0,
                        "hitFilterRuleList": [],
                        "id": 1452740,
                        "isDeletedField": 0,
                        "isPartitionField": 0,
                        "lodType": null,
                        "mapType": 0,
                        "name": "client_appid_name",
                        "operationCode": 0,
                        "ownerEmailPrefix": "maijiaming",
                        "paramIdList": [],
                        "showExpr": 1,
                        "visible": 1
                    },
                    {
                        "calcType": null,
                        "dataFormat": null,
                        "dataTypeName": "string",
                        "defaultDataTypeName": "string",
                        "descr": "",
                        "dimMetCategoryId": null,
                        "dimMetCategoryType": null,
                        "dimMetMixOrder": 16,
                        "dimMetOrder": 7,
                        "dimMetThirdPartyConf": null,
                        "dimMetVariety": 2,
                        "editable": 1,
                        "errCode": "ok",
                        "expr": "receiver_appid_name",
                        "exprAsDim": null,
                        "fieldList": "[\"receiver_appid_name\"]",
                        "fullExpr": "receiver_appid_name",
                        "groupType": 0,
                        "hitFilterRuleList": [],
                        "id": 1452741,
                        "isDeletedField": 0,
                        "isPartitionField": 0,
                        "lodType": null,
                        "mapType": 0,
                        "name": "receiver_appid_name",
                        "operationCode": 0,
                        "ownerEmailPrefix": "maijiaming",
                        "paramIdList": [],
                        "showExpr": 1,
                        "visible": 1
                    }
                ],
                "dimMetCategoryId": null,
                "dimMetCategoryType": null,
                "dimMetMixOrder": null,
                "dimMetOrder": 18,
                "dimMetThirdPartyConf": null,
                "id": 1453361,
                "layerType": 1,
                "mapType": 0,
                "name": "渠道维",
                "persisted": true
            },
            {
                "calcType": null,
                "dataFormat": null,
                "dataSetId": 928,
                "dimIdList": [
                    1452737,
                    1452739
                ],
                "dimList": [
                    {
                        "calcType": null,
                        "dataFormat": null,
                        "dataTypeName": "string",
                        "defaultDataTypeName": "string",
                        "descr": "",
                        "dimMetCategoryId": null,
                        "dimMetCategoryType": null,
                        "dimMetMixOrder": 2,
                        "dimMetOrder": 9,
                        "dimMetThirdPartyConf": null,
                        "dimMetVariety": 2,
                        "editable": 1,
                        "errCode": "ok",
                        "expr": "client_sdk_version",
                        "exprAsDim": null,
                        "fieldList": "[\"client_sdk_version\"]",
                        "fullExpr": "client_sdk_version",
                        "groupType": 0,
                        "hitFilterRuleList": [],
                        "id": 1452737,
                        "isDeletedField": 0,
                        "isPartitionField": 0,
                        "lodType": null,
                        "mapType": 0,
                        "name": "client_sdk_version",
                        "operationCode": 0,
                        "ownerEmailPrefix": "maijiaming",
                        "paramIdList": [],
                        "showExpr": 1,
                        "visible": 1
                    },
                    {
                        "calcType": null,
                        "dataFormat": null,
                        "dataTypeName": "string",
                        "defaultDataTypeName": "string",
                        "descr": "",
                        "dimMetCategoryId": null,
                        "dimMetCategoryType": null,
                        "dimMetMixOrder": 4,
                        "dimMetOrder": 10,
                        "dimMetThirdPartyConf": null,
                        "dimMetVariety": 2,
                        "editable": 1,
                        "errCode": "ok",
                        "expr": "receiver_sdk_version",
                        "exprAsDim": null,
                        "fieldList": "[\"receiver_sdk_version\"]",
                        "fullExpr": "receiver_sdk_version",
                        "groupType": 0,
                        "hitFilterRuleList": [],
                        "id": 1452739,
                        "isDeletedField": 0,
                        "isPartitionField": 0,
                        "lodType": null,
                        "mapType": 0,
                        "name": "receiver_sdk_version",
                        "operationCode": 0,
                        "ownerEmailPrefix": "maijiaming",
                        "paramIdList": [],
                        "showExpr": 1,
                        "visible": 1
                    }
                ],
                "dimMetCategoryId": null,
                "dimMetCategoryType": null,
                "dimMetMixOrder": null,
                "dimMetOrder": 27,
                "dimMetThirdPartyConf": null,
                "id": 1453370,
                "layerType": 1,
                "mapType": 0,
                "name": "版本维",
                "persisted": true
            },
            {
                "calcType": null,
                "dataFormat": null,
                "dataSetId": 928,
                "dimIdList": [
                    1452742
                ],
                "dimList": [
                    {
                        "calcType": null,
                        "dataFormat": null,
                        "dataTypeName": "string",
                        "defaultDataTypeName": "string",
                        "descr": "",
                        "dimMetCategoryId": null,
                        "dimMetCategoryType": null,
                        "dimMetMixOrder": 17,
                        "dimMetOrder": 12,
                        "dimMetThirdPartyConf": null,
                        "dimMetVariety": 2,
                        "editable": 1,
                        "errCode": "ok",
                        "expr": "receiver_sdk_type",
                        "exprAsDim": null,
                        "fieldList": "[\"receiver_sdk_type\"]",
                        "fullExpr": "receiver_sdk_type",
                        "groupType": 0,
                        "hitFilterRuleList": [],
                        "id": 1452742,
                        "isDeletedField": 0,
                        "isPartitionField": 0,
                        "lodType": null,
                        "mapType": 0,
                        "name": "receiver_sdk_type",
                        "operationCode": 0,
                        "ownerEmailPrefix": "maijiaming",
                        "paramIdList": [],
                        "showExpr": 1,
                        "visible": 1
                    }
                ],
                "dimMetCategoryId": null,
                "dimMetCategoryType": null,
                "dimMetMixOrder": null,
                "dimMetOrder": 28,
                "dimMetThirdPartyConf": null,
                "id": 1453371,
                "layerType": 1,
                "mapType": 0,
                "name": "收端类型维",
                "persisted": true
            }
        ],
        "labelConf": {
            "dataSetLabelType": 0,
            "labelParams": null,
            "subjectList": null
        },
        "linkConf": [],
        "nodeConf": [
            {
                "advanceSettings": [],
                "clusterName": "mc_lebo_data",
                "dataSourceId": 27,
                "dataSourceType": "maxcompute",
                "dbName": "lebo_data",
                "displayDbName": "lebo_data",
                "fields": [
                    {
                        "alias": "client_appid",
                        "comment": "",
                        "isDynamicPartition": false,
                        "isSelect": true,
                        "isSourceTableField": false,
                        "name": "client_appid",
                        "prepType": "string",
                        "status": 0,
                        "type": "string"
                    },
                    {
                        "alias": "client_sdk_version",
                        "comment": "",
                        "isDynamicPartition": false,
                        "isSelect": true,
                        "isSourceTableField": false,
                        "name": "client_sdk_version",
                        "prepType": "string",
                        "status": 0,
                        "type": "string"
                    },
                    {
                        "alias": "receiver_appid",
                        "comment": "",
                        "isDynamicPartition": false,
                        "isSelect": true,
                        "isSourceTableField": false,
                        "name": "receiver_appid",
                        "prepType": "string",
                        "status": 0,
                        "type": "string"
                    },
                    {
                        "alias": "receiver_sdk_version",
                        "comment": "",
                        "isDynamicPartition": false,
                        "isSelect": true,
                        "isSourceTableField": false,
                        "name": "receiver_sdk_version",
                        "prepType": "string",
                        "status": 0,
                        "type": "string"
                    },
                    {
                        "alias": "sn_1_succ_pv",
                        "comment": "",
                        "isDynamicPartition": false,
                        "isSelect": true,
                        "isSourceTableField": false,
                        "name": "sn_1_succ_pv",
                        "prepType": "long",
                        "status": 0,
                        "type": "bigint"
                    },
                    {
                        "alias": "sn_1_succ_uv",
                        "comment": "",
                        "isDynamicPartition": false,
                        "isSelect": true,
                        "isSourceTableField": false,
                        "name": "sn_1_succ_uv",
                        "prepType": "long",
                        "status": 0,
                        "type": "bigint"
                    },
                    {
                        "alias": "sn_2_succ_pv",
                        "comment": "",
                        "isDynamicPartition": false,
                        "isSelect": true,
                        "isSourceTableField": false,
                        "name": "sn_2_succ_pv",
                        "prepType": "long",
                        "status": 0,
                        "type": "bigint"
                    },
                    {
                        "alias": "sn_2_succ_uv",
                        "comment": "",
                        "isDynamicPartition": false,
                        "isSelect": true,
                        "isSourceTableField": false,
                        "name": "sn_2_succ_uv",
                        "prepType": "long",
                        "status": 0,
                        "type": "bigint"
                    },
                    {
                        "alias": "sn_3_succ_pv",
                        "comment": "",
                        "isDynamicPartition": false,
                        "isSelect": true,
                        "isSourceTableField": false,
                        "name": "sn_3_succ_pv",
                        "prepType": "long",
                        "status": 0,
                        "type": "bigint"
                    },
                    {
                        "alias": "sn_3_succ_uv",
                        "comment": "",
                        "isDynamicPartition": false,
                        "isSelect": true,
                        "isSourceTableField": false,
                        "name": "sn_3_succ_uv",
                        "prepType": "long",
                        "status": 0,
                        "type": "bigint"
                    },
                    {
                        "alias": "sn_100_succ_pv",
                        "comment": "",
                        "isDynamicPartition": false,
                        "isSelect": true,
                        "isSourceTableField": false,
                        "name": "sn_100_succ_pv",
                        "prepType": "long",
                        "status": 0,
                        "type": "bigint"
                    },
                    {
                        "alias": "sn_100_succ_uv",
                        "comment": "",
                        "isDynamicPartition": false,
                        "isSelect": true,
                        "isSourceTableField": false,
                        "name": "sn_100_succ_uv",
                        "prepType": "long",
                        "status": 0,
                        "type": "bigint"
                    },
                    {
                        "alias": "push_pv",
                        "comment": "",
                        "isDynamicPartition": false,
                        "isSelect": true,
                        "isSourceTableField": false,
                        "name": "push_pv",
                        "prepType": "long",
                        "status": 0,
                        "type": "bigint"
                    },
                    {
                        "alias": "receiver_uid",
                        "comment": "",
                        "isDynamicPartition": false,
                        "isSelect": true,
                        "isSourceTableField": false,
                        "name": "receiver_uid",
                        "prepType": "long",
                        "status": 0,
                        "type": "bigint"
                    },
                    {
                        "alias": "client_appid_name",
                        "comment": "",
                        "isDynamicPartition": false,
                        "isSelect": true,
                        "isSourceTableField": false,
                        "name": "client_appid_name",
                        "prepType": "string",
                        "status": 0,
                        "type": "string"
                    },
                    {
                        "alias": "receiver_appid_name",
                        "comment": "",
                        "isDynamicPartition": false,
                        "isSelect": true,
                        "isSourceTableField": false,
                        "name": "receiver_appid_name",
                        "prepType": "string",
                        "status": 0,
                        "type": "string"
                    },
                    {
                        "alias": "receiver_sdk_type",
                        "comment": "",
                        "isDynamicPartition": false,
                        "isSelect": true,
                        "isSourceTableField": false,
                        "name": "receiver_sdk_type",
                        "prepType": "string",
                        "status": 0,
                        "type": "string"
                    },
                    {
                        "alias": "p_date_lebo_data_dm_ad_cast_adpos_after_uv",
                        "comment": "",
                        "isDynamicPartition": false,
                        "isSelect": true,
                        "isSourceTableField": false,
                        "name": "p_date",
                        "prepType": "string",
                        "status": 0,
                        "type": "string"
                    },
                    {
                        "alias": "tag",
                        "comment": "",
                        "isDynamicPartition": false,
                        "isSelect": true,
                        "isSourceTableField": false,
                        "name": "tag",
                        "prepType": "string",
                        "status": 0,
                        "type": "string"
                    }
                ],
                "fullOption": false,
                "nodeId": "bae900be-1caa-4c03-a7c7-f0672e7898a4",
                "nodeType": "table",
                "params": {
                    "extractType": "{\"key\":\"full\"}"
                },
                "partitionConfList": [],
                "query": "",
                "schemaName": "dm_ad_cast_adpos_after_uv",
                "tableAlias": "dm_ad_cast_adpos_after_uv",
                "tableRowFilter": {},
                "tbId": "mc_lebo_data//lebo_data//dm_ad_cast_adpos_after_uv",
                "tbName": "dm_ad_cast_adpos_after_uv"
            }
        ],
        "parseEngine": 0,
        "syncConf": {
            "backtrackingConf": {
                "dateRange": {},
                "enable": 0
            },
            "doradoPriority": "normal",
            "frequency": "daily",
            "monitorConf": {
                "alarmRules": [
                    {
                        "failedAlarmItems": [
                            {
                                "item": "retry_failed"
                            }
                        ],
                        "id": 282,
                        "name": "auto_aeolus_rule_928_1687314978473",
                        "normalNoticeConf": [
                            {
                                "noticeChannel": "lark",
                                "users": [
                                    "maijiaming"
                                ]
                            }
                        ],
                        "resultAlarmItems": [],
                        "timeoutAlarmItems": []
                    }
                ]
            },
            "paramsConfList": [
                {
                    "name": "tqs.query.auto.retry.enable",
                    "value": "true"
                }
            ],
            "performanceSettings": {
                "chQueryParams": {
                    "openStrongConsistencyCheck": false
                },
                "clusterName": "rangers",
                "dataSourceId": 73,
                "driverName": "click_house",
                "partitionKey": [
                    "p_date"
                ],
                "primaryKeyList": [],
                "sampleKey": null,
                "sampleRate": 1.0,
                "shardKey": null
            },
            "retryInterval": 5,
            "retryNum": 1,
            "scheduleDay": "0",
            "scheduleTime": "00:00",
            "scheduleTimeType": 0,
            "slaDaytime": null,
            "slaStatus": 0,
            "syncType": 1,
            "ttl": 7,
            "upstreamSettings": {
                "dynamicPartitionConfList": [],
                "dynamicPartitionMode": false,
                "partitionConfList": [],
                "uniqueIndexList": []
            },
            "writePartition": 0,
            "yarnName": "offline"
        },
        "whereConf": {
            "nodeRowFilter": {},
            "requiredRowFilter": []
        }
    },
    "msg": "成功"
}