from random import Random


class Settings:
    SEED: int = 15
    BIAS_RESET_PROBABILITY: float = 0.05
    WEIGHT_RESET_PROBABILITY: float = 0.05
    AF_BIAS_PARTNER_INHERIT_PROBABILITY = 0.5
    CONNECTIONS_PARTNER_INHERIT_PROBABILITY: float = 0.5
    WEIGHT_MUTATION_PROBABILITY: float = 0.8
    BIAS_MUTATION_PROBABILITY: float = 0.5
    ACTIVATION_MUTATION_PROBABILITY: float = 0.1
    NEW_CONNECTION_PROBABILITY = 0.05
    NEW_NODE_PROBABILITY = 0.01
    EXCEED_PENALTY: float = 1
    DISJOINT_PENALTY: float = 1
    WEIGHT_DIFFERENCE_PENALTY: float = 1
    DIFF_THRESHOLD: float = 1
    PATIENCE: int = 100
    NUM_GENERATIONS = 10000

    rng: Random = Random(SEED)
