# Generated by Django 4.2.7 on 2023-11-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawranflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_analysis_complete',
            field=models.BooleanField(default=False),
        ),
    ]
