from enum import Enum


BLOB_DECODE_STANDARD = "Windows-1252"

INTEGRATOR_KEY_VAULT_NAME = "bonyusecrets"
NOTIFICATION_KEY_VAULT_NAME = "bonyu-notifications"
INTEGRATOR_SERVICE_BUS_TOPIC = "integration_apps_notification_topic"
DATALAKE_SERVICE_BUS_TOPIC = "integration_apps_notification_topic"
BROCKHAUS_FTP_FILES_PATH = "Artikel"
NOTIFICATION_TEMPLATE_PATH = "templates"
USER_PREFERENCES_TABLE = "UserPreferences"
CORRECTION_PREFIX = "correction_"


class EventType(Enum):
    PROCESSING_STARTED = "PROCESSING_STARTED"
    PROCESSING_FAILED = "PROCESSING_FAILED"
    PROCESSING_FINISHED = "PROCESSING_FINISHED"
    PROCESSING_FINISHED_WITH_RESTRICTIONS = "PROCESSING_FINISHED_WITH_RESTRICTIONS"


class DataProviders(Enum):
    BROCKHAUS = "BROCKHAUS"
    ABS = "ABS"
    KLOPOTEK = "KLOPOTEK"
