# coding: utf-8

"""
    Carrier API

    **Seaplane Global Messaging Service**  For information about authentication see [authentication](/docs/authentication)   # noqa: E501

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@seaplane.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import seaplane.gen.carrier
from seaplane.gen.carrier.models.switch_nested2 import SwitchNested2  # noqa: E501
from seaplane.gen.carrier.rest import ApiException


class TestSwitchNested2(unittest.TestCase):
    """SwitchNested2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SwitchNested2
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SwitchNested2`
        """
        model = seaplane.gen.carrier.models.switch_nested2.SwitchNested2()  # noqa: E501
        if include_optional :
            return SwitchNested2(
                switch = seaplane.gen.carrier.models.switch_nested2_switch.SwitchNested2_switch(
                    cases = [
                        seaplane.gen.carrier.models.switch_nested2_switch_cases_inner.SwitchNested2_switch_cases_inner(
                            check = 'this.foo < 5', 
                            output = null, )
                        ], )
            )
        else :
            return SwitchNested2(
        )
        """

    def testSwitchNested2(self):
        """Test SwitchNested2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
