# Generated by Django 2.2.5 on 2022-05-17 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0044_auto_20220513_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Для указания события используйте указатель `{event}`', max_length=1000, verbose_name='Заголовок')),
                ('body', models.TextField(help_text='Указатели: `{event}` - событие; `{user}` - ФИО пользователя; `{category}` - категория; `{locality}` - населённый пункт; `{date}` - дата события; `{time}` - время события', verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Шаблон письма',
                'verbose_name_plural': 'Шаблоны писем',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('event', models.CharField(blank=True, choices=[('NEW_VOTE_START', 'Начало нового голосования'), ('VOTE_END', 'Окончание голосования'), ('INITIATIVE_NEW_VOTE_START', 'Начало нового голосования по инициативе'), ('INITIATIVE_VOTE_END', 'Окончание голосования по инициативе'), ('DECISION_ON_INITIATIVE_PUBLICATION', 'Решение о публикации инициативы'), ('NEW_PLAN_PUBLICATION', 'Публикация нового плана'), ('REPAIR_WORK_PUBLICATION', 'Публикация ремонтных работ'), ('REPAIR_WORK_START', 'Начало ремонтных работ'), ('REPAIR_WORK_END', 'Окончание ремонтных работ'), ('NEWS_PUBLICATION', 'Публикация новостей')], default=None, max_length=255, null=True, verbose_name='Событие')),
                ('module', models.CharField(blank=True, choices=[('core', 'Общее'), ('voting', 'Голосования'), ('initiatives', 'Инициативы'), ('ap_works', 'Карта ремонтных работ'), ('plans', 'Планы')], default=None, max_length=255, null=True, verbose_name='Модуль')),
                ('category', models.CharField(help_text='модуль:Модель:pk', max_length=255, verbose_name='Категория')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.Locality', verbose_name='Населенный пункт')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.SubscriptionTemplate', verbose_name='Шаблон письма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь системы')),
            ],
            options={
                'verbose_name': 'Подписка пользователя',
                'verbose_name_plural': 'Подписки пользователей',
                'unique_together': {('user', 'event', 'module', 'template')},
            },
        ),
        migrations.CreateModel(
            name='NotificationSendingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('status', models.BooleanField(default=False, verbose_name='Статус отправки')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_sending_journal', to='subscriptions.Subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Запись об отправке оповещения',
                'verbose_name_plural': 'Журнал отправки оповещений',
                'ordering': ['timestamp'],
            },
        ),
    ]
