# coding: utf-8

"""
    Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference

    <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v12/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>   # noqa: E501

    The version of the OpenAPI document: v12
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from yahoo_display_test.configuration import Configuration


class AdGroupServiceBiddingScheme(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'campaign_bidding_strategy_type': 'AdGroupServiceCampaignBiddingStrategyType',
        'cpc_bidding_scheme': 'AdGroupServiceCpcBiddingScheme',
        'cpv_bidding_scheme': 'AdGroupServiceCpvBiddingScheme',
        'vcpm_bidding_scheme': 'AdGroupServiceVcpmBiddingScheme',
        'maximize_conversions_bidding_scheme': 'AdGroupServiceMaximizeConversionsBiddingScheme'
    }

    attribute_map = {
        'campaign_bidding_strategy_type': 'campaignBiddingStrategyType',
        'cpc_bidding_scheme': 'cpcBiddingScheme',
        'cpv_bidding_scheme': 'cpvBiddingScheme',
        'vcpm_bidding_scheme': 'vcpmBiddingScheme',
        'maximize_conversions_bidding_scheme': 'maximizeConversionsBiddingScheme'
    }

    def __init__(self, campaign_bidding_strategy_type=None, cpc_bidding_scheme=None, cpv_bidding_scheme=None, vcpm_bidding_scheme=None, maximize_conversions_bidding_scheme=None, local_vars_configuration=None):  # noqa: E501
        """AdGroupServiceBiddingScheme - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._campaign_bidding_strategy_type = None
        self._cpc_bidding_scheme = None
        self._cpv_bidding_scheme = None
        self._vcpm_bidding_scheme = None
        self._maximize_conversions_bidding_scheme = None
        self.discriminator = None

        self.campaign_bidding_strategy_type = campaign_bidding_strategy_type
        self.cpc_bidding_scheme = cpc_bidding_scheme
        self.cpv_bidding_scheme = cpv_bidding_scheme
        self.vcpm_bidding_scheme = vcpm_bidding_scheme
        self.maximize_conversions_bidding_scheme = maximize_conversions_bidding_scheme

    @property
    def campaign_bidding_strategy_type(self):
        """Gets the campaign_bidding_strategy_type of this AdGroupServiceBiddingScheme.  # noqa: E501


        :return: The campaign_bidding_strategy_type of this AdGroupServiceBiddingScheme.  # noqa: E501
        :rtype: AdGroupServiceCampaignBiddingStrategyType
        """
        return self._campaign_bidding_strategy_type

    @campaign_bidding_strategy_type.setter
    def campaign_bidding_strategy_type(self, campaign_bidding_strategy_type):
        """Sets the campaign_bidding_strategy_type of this AdGroupServiceBiddingScheme.


        :param campaign_bidding_strategy_type: The campaign_bidding_strategy_type of this AdGroupServiceBiddingScheme.  # noqa: E501
        :type: AdGroupServiceCampaignBiddingStrategyType
        """

        self._campaign_bidding_strategy_type = campaign_bidding_strategy_type

    @property
    def cpc_bidding_scheme(self):
        """Gets the cpc_bidding_scheme of this AdGroupServiceBiddingScheme.  # noqa: E501


        :return: The cpc_bidding_scheme of this AdGroupServiceBiddingScheme.  # noqa: E501
        :rtype: AdGroupServiceCpcBiddingScheme
        """
        return self._cpc_bidding_scheme

    @cpc_bidding_scheme.setter
    def cpc_bidding_scheme(self, cpc_bidding_scheme):
        """Sets the cpc_bidding_scheme of this AdGroupServiceBiddingScheme.


        :param cpc_bidding_scheme: The cpc_bidding_scheme of this AdGroupServiceBiddingScheme.  # noqa: E501
        :type: AdGroupServiceCpcBiddingScheme
        """

        self._cpc_bidding_scheme = cpc_bidding_scheme

    @property
    def cpv_bidding_scheme(self):
        """Gets the cpv_bidding_scheme of this AdGroupServiceBiddingScheme.  # noqa: E501


        :return: The cpv_bidding_scheme of this AdGroupServiceBiddingScheme.  # noqa: E501
        :rtype: AdGroupServiceCpvBiddingScheme
        """
        return self._cpv_bidding_scheme

    @cpv_bidding_scheme.setter
    def cpv_bidding_scheme(self, cpv_bidding_scheme):
        """Sets the cpv_bidding_scheme of this AdGroupServiceBiddingScheme.


        :param cpv_bidding_scheme: The cpv_bidding_scheme of this AdGroupServiceBiddingScheme.  # noqa: E501
        :type: AdGroupServiceCpvBiddingScheme
        """

        self._cpv_bidding_scheme = cpv_bidding_scheme

    @property
    def vcpm_bidding_scheme(self):
        """Gets the vcpm_bidding_scheme of this AdGroupServiceBiddingScheme.  # noqa: E501


        :return: The vcpm_bidding_scheme of this AdGroupServiceBiddingScheme.  # noqa: E501
        :rtype: AdGroupServiceVcpmBiddingScheme
        """
        return self._vcpm_bidding_scheme

    @vcpm_bidding_scheme.setter
    def vcpm_bidding_scheme(self, vcpm_bidding_scheme):
        """Sets the vcpm_bidding_scheme of this AdGroupServiceBiddingScheme.


        :param vcpm_bidding_scheme: The vcpm_bidding_scheme of this AdGroupServiceBiddingScheme.  # noqa: E501
        :type: AdGroupServiceVcpmBiddingScheme
        """

        self._vcpm_bidding_scheme = vcpm_bidding_scheme

    @property
    def maximize_conversions_bidding_scheme(self):
        """Gets the maximize_conversions_bidding_scheme of this AdGroupServiceBiddingScheme.  # noqa: E501


        :return: The maximize_conversions_bidding_scheme of this AdGroupServiceBiddingScheme.  # noqa: E501
        :rtype: AdGroupServiceMaximizeConversionsBiddingScheme
        """
        return self._maximize_conversions_bidding_scheme

    @maximize_conversions_bidding_scheme.setter
    def maximize_conversions_bidding_scheme(self, maximize_conversions_bidding_scheme):
        """Sets the maximize_conversions_bidding_scheme of this AdGroupServiceBiddingScheme.


        :param maximize_conversions_bidding_scheme: The maximize_conversions_bidding_scheme of this AdGroupServiceBiddingScheme.  # noqa: E501
        :type: AdGroupServiceMaximizeConversionsBiddingScheme
        """

        self._maximize_conversions_bidding_scheme = maximize_conversions_bidding_scheme

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdGroupServiceBiddingScheme):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AdGroupServiceBiddingScheme):
            return True

        return self.to_dict() != other.to_dict()
