# coding: utf-8

"""
    Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference

    <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v12/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>   # noqa: E501

    The version of the OpenAPI document: v12
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from yahoo_display_test.configuration import Configuration


class AudienceListServiceCombination(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'logical_operator': 'AudienceListServiceLogicalOperator',
        'audience_lists': 'list[AudienceListServiceData]'
    }

    attribute_map = {
        'logical_operator': 'logicalOperator',
        'audience_lists': 'audienceLists'
    }

    def __init__(self, logical_operator=None, audience_lists=None, local_vars_configuration=None):  # noqa: E501
        """AudienceListServiceCombination - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._logical_operator = None
        self._audience_lists = None
        self.discriminator = None

        self.logical_operator = logical_operator
        self.audience_lists = audience_lists

    @property
    def logical_operator(self):
        """Gets the logical_operator of this AudienceListServiceCombination.  # noqa: E501


        :return: The logical_operator of this AudienceListServiceCombination.  # noqa: E501
        :rtype: AudienceListServiceLogicalOperator
        """
        return self._logical_operator

    @logical_operator.setter
    def logical_operator(self, logical_operator):
        """Sets the logical_operator of this AudienceListServiceCombination.


        :param logical_operator: The logical_operator of this AudienceListServiceCombination.  # noqa: E501
        :type: AudienceListServiceLogicalOperator
        """

        self._logical_operator = logical_operator

    @property
    def audience_lists(self):
        """Gets the audience_lists of this AudienceListServiceCombination.  # noqa: E501


        :return: The audience_lists of this AudienceListServiceCombination.  # noqa: E501
        :rtype: list[AudienceListServiceData]
        """
        return self._audience_lists

    @audience_lists.setter
    def audience_lists(self, audience_lists):
        """Sets the audience_lists of this AudienceListServiceCombination.


        :param audience_lists: The audience_lists of this AudienceListServiceCombination.  # noqa: E501
        :type: list[AudienceListServiceData]
        """

        self._audience_lists = audience_lists

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AudienceListServiceCombination):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AudienceListServiceCombination):
            return True

        return self.to_dict() != other.to_dict()
