# coding: utf-8

"""
    Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference

    <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v12/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>   # noqa: E501

    The version of the OpenAPI document: v12
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from yahoo_display_test.configuration import Configuration


class GuaranteedAdGroupAdServiceBrandPanelPanoramaPanelSwitch(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'display_order': 'int',
        'final_url': 'str',
        'media_id': 'int',
        'switch_media_id': 'int'
    }

    attribute_map = {
        'display_order': 'displayOrder',
        'final_url': 'finalUrl',
        'media_id': 'mediaId',
        'switch_media_id': 'switchMediaId'
    }

    def __init__(self, display_order=None, final_url=None, media_id=None, switch_media_id=None, local_vars_configuration=None):  # noqa: E501
        """GuaranteedAdGroupAdServiceBrandPanelPanoramaPanelSwitch - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._display_order = None
        self._final_url = None
        self._media_id = None
        self._switch_media_id = None
        self.discriminator = None

        self.display_order = display_order
        self.final_url = final_url
        self.media_id = media_id
        self.switch_media_id = switch_media_id

    @property
    def display_order(self):
        """Gets the display_order of this GuaranteedAdGroupAdServiceBrandPanelPanoramaPanelSwitch.  # noqa: E501

        <div lang=\"ja\"> パネルの表示順です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。<br> ※指定しない場合は自動で設定されます。 </div> <div lang=\"en\"> Panel display order.<br> This field will be returned in the response, it will be ignored on input.<br> *If not specified, it will be set automatically. </div>   # noqa: E501

        :return: The display_order of this GuaranteedAdGroupAdServiceBrandPanelPanoramaPanelSwitch.  # noqa: E501
        :rtype: int
        """
        return self._display_order

    @display_order.setter
    def display_order(self, display_order):
        """Sets the display_order of this GuaranteedAdGroupAdServiceBrandPanelPanoramaPanelSwitch.

        <div lang=\"ja\"> パネルの表示順です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。<br> ※指定しない場合は自動で設定されます。 </div> <div lang=\"en\"> Panel display order.<br> This field will be returned in the response, it will be ignored on input.<br> *If not specified, it will be set automatically. </div>   # noqa: E501

        :param display_order: The display_order of this GuaranteedAdGroupAdServiceBrandPanelPanoramaPanelSwitch.  # noqa: E501
        :type: int
        """

        self._display_order = display_order

    @property
    def final_url(self):
        """Gets the final_url of this GuaranteedAdGroupAdServiceBrandPanelPanoramaPanelSwitch.  # noqa: E501

        <div lang=\"ja\">最終リンク先URLです。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\">Final URL.<br> This field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :return: The final_url of this GuaranteedAdGroupAdServiceBrandPanelPanoramaPanelSwitch.  # noqa: E501
        :rtype: str
        """
        return self._final_url

    @final_url.setter
    def final_url(self, final_url):
        """Sets the final_url of this GuaranteedAdGroupAdServiceBrandPanelPanoramaPanelSwitch.

        <div lang=\"ja\">最終リンク先URLです。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\">Final URL.<br> This field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :param final_url: The final_url of this GuaranteedAdGroupAdServiceBrandPanelPanoramaPanelSwitch.  # noqa: E501
        :type: str
        """

        self._final_url = final_url

    @property
    def media_id(self):
        """Gets the media_id of this GuaranteedAdGroupAdServiceBrandPanelPanoramaPanelSwitch.  # noqa: E501

        <div lang=\"ja\"> メディアIDです。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Media ID.<br> This field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :return: The media_id of this GuaranteedAdGroupAdServiceBrandPanelPanoramaPanelSwitch.  # noqa: E501
        :rtype: int
        """
        return self._media_id

    @media_id.setter
    def media_id(self, media_id):
        """Sets the media_id of this GuaranteedAdGroupAdServiceBrandPanelPanoramaPanelSwitch.

        <div lang=\"ja\"> メディアIDです。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Media ID.<br> This field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :param media_id: The media_id of this GuaranteedAdGroupAdServiceBrandPanelPanoramaPanelSwitch.  # noqa: E501
        :type: int
        """

        self._media_id = media_id

    @property
    def switch_media_id(self):
        """Gets the switch_media_id of this GuaranteedAdGroupAdServiceBrandPanelPanoramaPanelSwitch.  # noqa: E501

        <div lang=\"ja\"> スイッチ画像のメディアIDです。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Media ID of switch image.<br> This field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :return: The switch_media_id of this GuaranteedAdGroupAdServiceBrandPanelPanoramaPanelSwitch.  # noqa: E501
        :rtype: int
        """
        return self._switch_media_id

    @switch_media_id.setter
    def switch_media_id(self, switch_media_id):
        """Sets the switch_media_id of this GuaranteedAdGroupAdServiceBrandPanelPanoramaPanelSwitch.

        <div lang=\"ja\"> スイッチ画像のメディアIDです。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 </div> <div lang=\"en\"> Media ID of switch image.<br> This field will be returned in the response, it will be ignored on input. </div>   # noqa: E501

        :param switch_media_id: The switch_media_id of this GuaranteedAdGroupAdServiceBrandPanelPanoramaPanelSwitch.  # noqa: E501
        :type: int
        """

        self._switch_media_id = switch_media_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GuaranteedAdGroupAdServiceBrandPanelPanoramaPanelSwitch):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GuaranteedAdGroupAdServiceBrandPanelPanoramaPanelSwitch):
            return True

        return self.to_dict() != other.to_dict()
