# Generated by Django 2.2.5 on 2021-08-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="objecttype",
            options={
                "verbose_name": "Тип объекта",
                "verbose_name_plural": "Типы объектов",
            },
        ),
        migrations.AlterModelOptions(
            name="problematic",
            options={
                "verbose_name": "Проблематика",
                "verbose_name_plural": "Проблематики",
            },
        ),
        migrations.AlterModelOptions(
            name="qrgenerator",
            options={
                "verbose_name": "Генератор QR-кода",
                "verbose_name_plural": "Генераторы QR-кода",
            },
        ),
        migrations.AlterField(
            model_name="qrgenerator",
            name="qr_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
