# Generated by Django 2.2.5 on 2021-08-16 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_auto_20210816_1146"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qrgenerator",
            options={
                "verbose_name": "Данные QR-кода",
                "verbose_name_plural": "Данные QR-кодов",
            },
        ),
        migrations.RemoveField(
            model_name="qrgenerator",
            name="qr_image",
        ),
        migrations.AddField(
            model_name="qrgenerator",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="qrgenerator",
            name="last_modified_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
        migrations.AlterField(
            model_name="qrgenerator",
            name="email_of_responsible_person",
            field=models.EmailField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Электронный адрес ответственного лица",
            ),
        ),
        migrations.AlterField(
            model_name="qrgenerator",
            name="object_address",
            field=models.CharField(
                blank=True, max_length=600, null=True, verbose_name="Адрес объекта"
            ),
        ),
        migrations.AlterField(
            model_name="qrgenerator",
            name="object_name",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Название объекта"
            ),
        ),
        migrations.AddIndex(
            model_name="objecttype",
            index=models.Index(fields=["id"], name="feedback_ob_id_7749cf_idx"),
        ),
        migrations.AddIndex(
            model_name="problematic",
            index=models.Index(fields=["id"], name="feedback_pr_id_14995f_idx"),
        ),
        migrations.AddIndex(
            model_name="qrgenerator",
            index=models.Index(fields=["id"], name="feedback_qr_id_20380b_idx"),
        ),
    ]
