# Generated by Django 2.2.5 on 2021-08-16 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0003_auto_20210816_1628"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opinion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_name",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Название объекта",
                    ),
                ),
                (
                    "object_address",
                    models.CharField(
                        blank=True,
                        max_length=600,
                        null=True,
                        verbose_name="Адрес объекта",
                    ),
                ),
                (
                    "email_of_responsible_person",
                    models.EmailField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Электронный адрес ответственного лица",
                    ),
                ),
                (
                    "text",
                    models.TextField(blank=True, null=True, verbose_name="Тект мнения"),
                ),
                (
                    "placement_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата размещения"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Новое"),
                            ("UNDER_CONSIDERATION", "На рассмотрении"),
                            ("IN_WORK", "В работе"),
                            ("UNDER_REVIEW", "На проверке"),
                            ("RESPONSE_SENT", "Направлен ответ"),
                        ],
                        max_length=100,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "object_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opinions",
                        to="feedback.ObjectType",
                        verbose_name="Тип объекта",
                    ),
                ),
                (
                    "problematic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opinions",
                        to="feedback.Problematic",
                        verbose_name="Проблематика",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мнение",
                "verbose_name_plural": "Мнения",
            },
        ),
        migrations.AddIndex(
            model_name="opinion",
            index=models.Index(fields=["id"], name="feedback_op_id_8d31be_idx"),
        ),
    ]
