# Generated by Django 2.2.5 on 2021-08-17 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0009_auto_20210817_1738"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opinion",
            name="email_of_responsible_person",
            field=models.EmailField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Электронный адрес ответственного лица",
            ),
        ),
        migrations.AlterField(
            model_name="opinion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
        ),
    ]
