# Generated by Django 2.2.5 on 2021-08-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0012_auto_20210818_1156"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opinion",
            name="user_phone",
            field=models.CharField(
                blank="True", max_length=20, verbose_name="Номер телефона пользователя"
            ),
        ),
    ]
