# Generated by Django 2.2.5 on 2021-08-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0014_auto_20210818_1325"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opinion",
            name="creation_date",
        ),
    ]
