# Generated by Django 2.2.5 on 2021-08-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0015_remove_opinion_creation_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opinion",
            name="last_modified_date",
        ),
        migrations.RemoveField(
            model_name="opinion",
            name="uploaded_image",
        ),
        migrations.RemoveField(
            model_name="opinion",
            name="user_email",
        ),
        migrations.RemoveField(
            model_name="opinion",
            name="user_phone",
        ),
        migrations.AlterField(
            model_name="opinion",
            name="object_address",
            field=models.CharField(
                blank=True, max_length=600, null=True, verbose_name="Адрес объекта"
            ),
        ),
    ]
