# Generated by Django 2.2.5 on 2021-09-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0020_auto_20210906_1012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortlink",
            name="full_link",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="Ссылка"
            ),
        ),
        migrations.AlterField(
            model_name="shortlink",
            name="short_key",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Короткий ключ",
            ),
        ),
    ]
