# Generated by Django 2.2.5 on 2021-09-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0021_auto_20210906_1025"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortlink",
            name="full_link",
            field=models.TextField(
                blank=True, max_length=1500, null=True, verbose_name="Ссылка"
            ),
        ),
    ]
