# Generated by Django 2.2.5 on 2023-08-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_auto_20230802_1004'),
        ('feedback', '0022_auto_20210906_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='locality',
            field=models.ManyToManyField(blank=True, null=True, related_name='opinions', to='core.Locality', verbose_name='Муниципальные образования'),
        ),
    ]
