# Generated by Django 2.2.5 on 2023-08-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0025_merge_20230802_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='municipal_formation',
        ),
        migrations.RemoveField(
            model_name='qrgenerator',
            name='municipal_formation',
        ),
    ]
