# Generated by Django 2.2.5 on 2023-09-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0027_qrgenerator_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='locality',
            field=models.ManyToManyField(blank=True, related_name='opinions', to='core.Locality', verbose_name='Муниципальные образования'),
        ),
        migrations.AlterField(
            model_name='qrgenerator',
            name='locality',
            field=models.ManyToManyField(blank=True, related_name='qrgenerators', to='core.Locality', verbose_name='Муниципальные образования'),
        ),
    ]
