# coding: utf-8

"""
    VRt.Studio [ST]

    Veeroute Studio API.  # Description  Server part of the studio.  ## Entity relationship diagram  ![erd](../uml/studio.svg)

    The version of the OpenAPI document: 6.16.2177
    Contact: servicedesk@veeroute.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class BasicTracksType(str, Enum):
    """
    Tracks type. 
    """

    """
    allowed enum values
    """
    LINE = 'LINE'
    ROAD = 'ROAD'

    @classmethod
    def from_json(cls, json_str: str) -> BasicTracksType:
        """Create an instance of BasicTracksType from a JSON string"""
        return BasicTracksType(json.loads(json_str))


