# Generated by Django 2.2.5 on 2020-06-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0007_auto_20200628_1227"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiativeoperatorcommunication",
            name="moderator_viewed",
            field=models.BooleanField(
                default=False, verbose_name="Просмотрено модератором"
            ),
        ),
        migrations.AddField(
            model_name="initiativeoperatorcommunication",
            name="operator_viewed",
            field=models.BooleanField(
                default=False, verbose_name="Просмотрено оператором"
            ),
        ),
        migrations.AddField(
            model_name="initiativeoperatorcommunication",
            name="user_viewed",
            field=models.BooleanField(
                default=False, verbose_name="Просмотрено пользователем"
            ),
        ),
    ]
