from pebbleauthclient.auth import auth

auth_token = auth("eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImVudGl0bGVtZW50Ijo5OTQsImtpZCI6IjEzQ1pmSlhkblVKWlhBLW13MGhnSEI2bjl4ODVqQTVZeDRvdjNRTmlBNmsifQ.eyJpc3MiOiJEaW5vQ2hpZXNhLmdpdGh1Yi5pbyIsInN1YiI6ImFsbWEiLCJhdWQiOiJraW5hIiwiaWF0IjoxNzAwNzM0OTUwLCJleHAiOjE3MDA3MzU1NTB9.cF6bYJnwI-wHYr2qOrfz1d5eYv-hMLIULAXntAaKBn4WUarKOG-ExZ5r9ZvJM-SU0uWeFiiuoPNiD1oi-6CTVobqUMbTxwq_FeuM8XCxlGcmj-yUv_tSAkThG7cK774vHyXaZ5-liXnwll8G5i6RQUSyU2Jwh9MmA-fuEKnfLqWdqOL8NLyvYiJnRQrniuaPk0gGa2RXWu7RJpLMkU4kspJJD9eKFiyVAtG3AEOycvdRMdLzgE10F1YuNZ9RrPtBIOgX4kctkm3FMEhYVgPynbL9V-2neS2hfI8pl_qmU7X3MXiFrZUcrElQ6D8w0bkEHrp7CRS_txvwsczsvtxHhA")

print(auth_token)

print(auth_token.get_user())

print(auth_token.get_authenticated_licence())
