import fileoperator

files = ["testdir/test.txt.part0", "testdir/test.txt.part1"]

# fileoperator.open_exe("/Applications/Google Chrome.app/")
# fileoperator.close_exe("/Applications/Google Chrome.app/")
# fileoperator.create_file("./test.txt")
# print(fileoperator.write_file("./test.txt", "Hi Mom!"))
# print(fileoperator.read_file("./test.txt"))
# fileoperator.copy_file_to_clipboard("./test.txt")  #Hi Mom!
# fileoperator.append_data_to_file("./test.txt", " Hi Dad!")
# fileoperator.make_dir("./testdir")
# fileoperator.move_file("./test.txt", "testdir/test.txt")
# print(fileoperator.get_file_size("testdir/test.txt"))
# print(fileoperator.does_file_exist("testdir/test.txt"))
# print(fileoperator.list_dir_files("../"))
# print(fileoperator.get_file_perm("testdir/test.txt"))
# print(fileoperator.get_file_type("testdir/test.txt"))
# print(fileoperator.get_num_lines("testdir/test.txt"))
# print(fileoperator.get_num_words("testdir/test.txt"))
# print(fileoperator.get_word_freq("testdir/test.txt", "Hi"))
# print(fileoperator.get_num_chars("testdir/test.txt"))
# print(fileoperator.get_char_freq("testdir/test.txt", "H"))
# fileoperator.create_temp_file()
# print(fileoperator.is_dir_empty("./"))
# print(fileoperator.get_system_usage("./"))
# fileoperator.monitor_file("testdir/test.txt")
# print(fileoperator.get_base64("testdir/test.txt"))
# fileoperator.create_symbolic_link("testdir/test.txt", "testdir/test")
# fileoperator.split_file("testdir/test.txt", 2)
# fileoperator.merge_file(files, "testdir/testmerge.txt")
# fileoperator.replace_data("testdir/test.txt", "Hi Dad!", "Bye Dad!")
# fileoperator.monitor_dir("./")
# print(fileoperator.does_dir_exist("testdir"))
# print(fileoperator.does_data_exist("testdir/test.txt", "Hi Mom"))
# print(fileoperator.compare_files("testdir/test.txt", "testdir/test.txt.part0"))
# concat = ["testdir/test.txt.part0", "testdir/test.txt.part1"]
# fileoperator.concat_files(files, "testdir/testconcat.txt")
# print(get_data_from_file("testdir/test.txt", "Bye Mom"))
# fileoperator.delete_file("testdir/test.txt.part0")
# fileoperator.delete_dir("testdir/testdir2")
# fileoperator.change_file_perm("testdir/test.txt", 777)
