# Generated by Django 2.2.5 on 2023-09-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalsystemtoken',
            name='permission',
            field=models.ManyToManyField(blank=True, related_name='external_system_token', to='auth.Permission', verbose_name='разрешения'),
        ),
    ]
