# Generated by Django 2.2.5 on 2023-09-20 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integration', '0005_custompermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSynchronization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synchorized_user_id', models.TextField(verbose_name='id пользователя во внешней системе')),
                ('synchonization_date', models.DateTimeField(auto_now_add=True)),
                ('external_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_synchronization', to='integration.ExternalSystemToken', verbose_name='внешняя ИС')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_synchronization', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'синхронизация пользователя',
                'verbose_name_plural': 'синхронизации пользователей',
                'unique_together': {('user', 'synchorized_user_id')},
            },
        ),
    ]
