# Generated by Django 5.0b1 on 2023-11-15 03:45

import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0003_alter_template_is_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="is_completed",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.lookups.Exact(
                    models.F("status"), models.Value("c")
                ),
            ),
        ),
    ]
