# Generated by Django 2.2.5 on 2020-09-03 09:42

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0005_auto_20200720_1637"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(verbose_name="Адрес")),
                (
                    "gis_center",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="Позиция"
                    ),
                ),
                (
                    "gis_border",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Граница"
                    ),
                ),
            ],
            options={
                "verbose_name": "Адрес",
                "verbose_name_plural": "Адреса",
            },
        ),
        migrations.CreateModel(
            name="RejectReason",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
            ],
            options={
                "verbose_name": "Причина отказа",
                "verbose_name_plural": "Причины отказа",
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="initiatives", verbose_name="Файл"),
                ),
                (
                    "type",
                    models.TextField(
                        choices=[("IMAGE", "Изображение"), ("DOCUMENT", "Документ")],
                        verbose_name="Тип файла",
                    ),
                ),
                ("name", models.TextField(verbose_name="Имя файла")),
                (
                    "order",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Порядок"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл",
                "verbose_name_plural": "Файлы",
            },
        ),
        migrations.CreateModel(
            name="Contractor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Наименование")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Адрес электронной почты",
                    ),
                ),
                (
                    "locality",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="core.Locality",
                        verbose_name="Муниципальные образования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Исполнитель",
                "verbose_name_plural": "Исполнители",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Наименование")),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="#000000",
                        max_length=7,
                        null=True,
                        verbose_name="Цвет html",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="(максимальный размер файла 5 МБ)",
                        null=True,
                        upload_to="",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="appeals.Category",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Appeal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.TextField(verbose_name="Регистрационный номер")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                ("phone_number", models.TextField(verbose_name="Номер телефона")),
                (
                    "creation_date_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание проблемы")),
                (
                    "is_public",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Публичное"
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("MODERATION", "Модерирование"),
                            ("MODERATION_REJECTED", "Отклонено"),
                            ("MODERATION_ACCEPTED", "На рассмотрении"),
                            ("IN_PROGRESS", "В работе"),
                        ],
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "moderation_pass_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения модерации"
                    ),
                ),
                (
                    "in_progress_begin_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата постановки в работу"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appeals.Category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "contractor",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="appeals.Contractor",
                        verbose_name="Исполнители",
                    ),
                ),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True, null=True, to="appeals.File", verbose_name="Файлы"
                    ),
                ),
                (
                    "locality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.Locality",
                        verbose_name="Муниципальное образование",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appeals.Location",
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Заявитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обращение",
                "verbose_name_plural": "Обращения",
            },
        ),
    ]
