# Generated by Django 2.2.5 on 2020-09-08 03:38

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("appeals", "0003_category_icon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appeal",
            old_name="contractor",
            new_name="contractors",
        ),
        migrations.AddField(
            model_name="appeal",
            name="responded_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата ответа на обращение"
            ),
        ),
        migrations.AlterField(
            model_name="appeal",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("MODERATION", "Модерирование"),
                    ("MODERATION_REJECTED", "Отклонено"),
                    ("MODERATION_ACCEPTED", "На рассмотрении"),
                    ("IN_PROGRESS", "В работе"),
                    ("RESPONDED", "Получен ответ"),
                ],
                max_length=50,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="appeals", verbose_name="Файл"),
        ),
    ]
