# Generated by Django 2.2.5 on 2020-09-08 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appeals", "0004_auto_20200908_1038"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppealResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="Дата-время")),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True, to="appeals.File", verbose_name="Файлы"
                    ),
                ),
                (
                    "initiative",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="appeals.Appeal",
                        verbose_name="Обращение",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправитель",
                    ),
                ),
            ],
        ),
    ]
