# Generated by Django 2.2.5 on 2020-09-10 09:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appeals", "0007_auto_20200909_1219"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appeal",
            name="location",
        ),
        migrations.AddField(
            model_name="appeal",
            name="address",
            field=models.TextField(blank=True, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="appeal",
            name="gis_point",
            field=django.contrib.gis.db.models.fields.PointField(
                default="POINT(0.0 0.0)", srid=4326, verbose_name="Точка на карте"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
