# Generated by Django 2.2.5 on 2020-09-14 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_user_phone"),
        ("appeals", "0008_auto_20200910_1601"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appealresponse",
            options={
                "verbose_name": "Ответ на обращение",
                "verbose_name_plural": "Ответы на обращения",
            },
        ),
        migrations.CreateModel(
            name="DepartmentCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appeals.Category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.Department",
                        verbose_name="Ведомство",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория ведомства",
                "verbose_name_plural": "Категории ведомства",
                "unique_together": {("department", "category")},
            },
        ),
    ]
