# Generated by Django 2.2.5 on 2020-09-28 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_user_phone"),
        ("appeals", "0012_appealstatechange_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="appealresponse",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Department",
                verbose_name="Ведомство",
            ),
            preserve_default=False,
        ),
    ]
