# Generated by Django 2.2.5 on 2020-10-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appeals", "0014_appealstatechange_second_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True,
                help_text="(максимальный размер файла 5 МБ)",
                null=True,
                upload_to="appeals",
                verbose_name="Иконка",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="(максимальный размер файла 5 МБ)",
                null=True,
                upload_to="appeals",
                verbose_name="Изображение",
            ),
        ),
    ]
