# Generated by Django 2.2.5 on 2021-02-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appeals", "0015_auto_20201008_1741"),
    ]

    operations = [
        migrations.AddField(
            model_name="appeal",
            name="create_by_operator",
            field=models.BooleanField(default=False, verbose_name="Создано оператором"),
        ),
    ]
