# Generated by Django 2.2.5 on 2023-07-23 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0020_auto_20230723_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentcategory',
            name='department',
            field=models.ForeignKey(limit_choices_to={'status': 'IS_ACTIVE'}, on_delete=django.db.models.deletion.CASCADE, to='core.Department', verbose_name='Ведомство'),
        ),
    ]
