
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-20T14:04:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "eb552eef7a8381e47a38ce0694244700693cb978",
 "version": "2.18.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
