# Generated by Django 2.2.5 on 2022-09-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0021_initiative_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiativeacceptingsettings',
            name='type',
            field=models.CharField(choices=[('REGIONAL', 'Региональная'), ('MUNICIPAL', 'Муниципальная')], default='MUNICIPAL', max_length=20, verbose_name='Уровень реализации'),
            preserve_default=False,
        ),
    ]
