# coding: utf-8

"""
    Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference

    <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v12/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>   # noqa: E501

    The version of the OpenAPI document: v12
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from yahoo_search_test.configuration import Configuration


class PageFeedAssetServiceDownloadJob(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'account_id': 'int',
        'bulk_encoding': 'PageFeedAssetServiceBulkEncoding',
        'bulk_lang': 'PageFeedAssetServiceBulkLang',
        'bulk_output': 'PageFeedAssetServiceBulkOutput',
        'download_job_status': 'PageFeedAssetServiceDownloadJobStatus',
        'end_date': 'str',
        'page_feed_asset_set_id': 'int',
        'job_id': 'int',
        'progress': 'int',
        'start_date': 'str'
    }

    attribute_map = {
        'account_id': 'accountId',
        'bulk_encoding': 'bulkEncoding',
        'bulk_lang': 'bulkLang',
        'bulk_output': 'bulkOutput',
        'download_job_status': 'downloadJobStatus',
        'end_date': 'endDate',
        'page_feed_asset_set_id': 'pageFeedAssetSetId',
        'job_id': 'jobId',
        'progress': 'progress',
        'start_date': 'startDate'
    }

    def __init__(self, account_id=None, bulk_encoding=None, bulk_lang=None, bulk_output=None, download_job_status=None, end_date=None, page_feed_asset_set_id=None, job_id=None, progress=None, start_date=None, local_vars_configuration=None):  # noqa: E501
        """PageFeedAssetServiceDownloadJob - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._account_id = None
        self._bulk_encoding = None
        self._bulk_lang = None
        self._bulk_output = None
        self._download_job_status = None
        self._end_date = None
        self._page_feed_asset_set_id = None
        self._job_id = None
        self._progress = None
        self._start_date = None
        self.discriminator = None

        self.account_id = account_id
        self.bulk_encoding = bulk_encoding
        self.bulk_lang = bulk_lang
        self.bulk_output = bulk_output
        self.download_job_status = download_job_status
        self.end_date = end_date
        self.page_feed_asset_set_id = page_feed_asset_set_id
        self.job_id = job_id
        self.progress = progress
        self.start_date = start_date

    @property
    def account_id(self):
        """Gets the account_id of this PageFeedAssetServiceDownloadJob.  # noqa: E501

        <div lang=\"ja\">アカウントIDです。<br> このフィールドは必須です。</div> <div lang=\"en\">Account ID.<br> This field is required.</div>   # noqa: E501

        :return: The account_id of this PageFeedAssetServiceDownloadJob.  # noqa: E501
        :rtype: int
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this PageFeedAssetServiceDownloadJob.

        <div lang=\"ja\">アカウントIDです。<br> このフィールドは必須です。</div> <div lang=\"en\">Account ID.<br> This field is required.</div>   # noqa: E501

        :param account_id: The account_id of this PageFeedAssetServiceDownloadJob.  # noqa: E501
        :type: int
        """

        self._account_id = account_id

    @property
    def bulk_encoding(self):
        """Gets the bulk_encoding of this PageFeedAssetServiceDownloadJob.  # noqa: E501


        :return: The bulk_encoding of this PageFeedAssetServiceDownloadJob.  # noqa: E501
        :rtype: PageFeedAssetServiceBulkEncoding
        """
        return self._bulk_encoding

    @bulk_encoding.setter
    def bulk_encoding(self, bulk_encoding):
        """Sets the bulk_encoding of this PageFeedAssetServiceDownloadJob.


        :param bulk_encoding: The bulk_encoding of this PageFeedAssetServiceDownloadJob.  # noqa: E501
        :type: PageFeedAssetServiceBulkEncoding
        """

        self._bulk_encoding = bulk_encoding

    @property
    def bulk_lang(self):
        """Gets the bulk_lang of this PageFeedAssetServiceDownloadJob.  # noqa: E501


        :return: The bulk_lang of this PageFeedAssetServiceDownloadJob.  # noqa: E501
        :rtype: PageFeedAssetServiceBulkLang
        """
        return self._bulk_lang

    @bulk_lang.setter
    def bulk_lang(self, bulk_lang):
        """Sets the bulk_lang of this PageFeedAssetServiceDownloadJob.


        :param bulk_lang: The bulk_lang of this PageFeedAssetServiceDownloadJob.  # noqa: E501
        :type: PageFeedAssetServiceBulkLang
        """

        self._bulk_lang = bulk_lang

    @property
    def bulk_output(self):
        """Gets the bulk_output of this PageFeedAssetServiceDownloadJob.  # noqa: E501


        :return: The bulk_output of this PageFeedAssetServiceDownloadJob.  # noqa: E501
        :rtype: PageFeedAssetServiceBulkOutput
        """
        return self._bulk_output

    @bulk_output.setter
    def bulk_output(self, bulk_output):
        """Sets the bulk_output of this PageFeedAssetServiceDownloadJob.


        :param bulk_output: The bulk_output of this PageFeedAssetServiceDownloadJob.  # noqa: E501
        :type: PageFeedAssetServiceBulkOutput
        """

        self._bulk_output = bulk_output

    @property
    def download_job_status(self):
        """Gets the download_job_status of this PageFeedAssetServiceDownloadJob.  # noqa: E501


        :return: The download_job_status of this PageFeedAssetServiceDownloadJob.  # noqa: E501
        :rtype: PageFeedAssetServiceDownloadJobStatus
        """
        return self._download_job_status

    @download_job_status.setter
    def download_job_status(self, download_job_status):
        """Sets the download_job_status of this PageFeedAssetServiceDownloadJob.


        :param download_job_status: The download_job_status of this PageFeedAssetServiceDownloadJob.  # noqa: E501
        :type: PageFeedAssetServiceDownloadJobStatus
        """

        self._download_job_status = download_job_status

    @property
    def end_date(self):
        """Gets the end_date of this PageFeedAssetServiceDownloadJob.  # noqa: E501

        <div lang=\"ja\">ジョブの終了日です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。<br> 形式：yyyyMMddHHmmss</div><div lang=\"en\">End date of job.<br> Although this field will be returned in the response, it will be ignored on input.  <br> Format:yyyyMMddHHmmss</div>   # noqa: E501

        :return: The end_date of this PageFeedAssetServiceDownloadJob.  # noqa: E501
        :rtype: str
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this PageFeedAssetServiceDownloadJob.

        <div lang=\"ja\">ジョブの終了日です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。<br> 形式：yyyyMMddHHmmss</div><div lang=\"en\">End date of job.<br> Although this field will be returned in the response, it will be ignored on input.  <br> Format:yyyyMMddHHmmss</div>   # noqa: E501

        :param end_date: The end_date of this PageFeedAssetServiceDownloadJob.  # noqa: E501
        :type: str
        """

        self._end_date = end_date

    @property
    def page_feed_asset_set_id(self):
        """Gets the page_feed_asset_set_id of this PageFeedAssetServiceDownloadJob.  # noqa: E501

        <div lang=\"ja\">ページフィードアセットセットIDです。<br> このフィールドは必須です。</div> <div lang=\"en\">PageFeedAssetSet ID.<br> This field is required.</div>   # noqa: E501

        :return: The page_feed_asset_set_id of this PageFeedAssetServiceDownloadJob.  # noqa: E501
        :rtype: int
        """
        return self._page_feed_asset_set_id

    @page_feed_asset_set_id.setter
    def page_feed_asset_set_id(self, page_feed_asset_set_id):
        """Sets the page_feed_asset_set_id of this PageFeedAssetServiceDownloadJob.

        <div lang=\"ja\">ページフィードアセットセットIDです。<br> このフィールドは必須です。</div> <div lang=\"en\">PageFeedAssetSet ID.<br> This field is required.</div>   # noqa: E501

        :param page_feed_asset_set_id: The page_feed_asset_set_id of this PageFeedAssetServiceDownloadJob.  # noqa: E501
        :type: int
        """

        self._page_feed_asset_set_id = page_feed_asset_set_id

    @property
    def job_id(self):
        """Gets the job_id of this PageFeedAssetServiceDownloadJob.  # noqa: E501

        <div lang=\"ja\">ジョブIDです。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。</div> <div lang=\"en\">Job ID.<br> Although this field will be returned in the response, it will be ignored on input.</div>   # noqa: E501

        :return: The job_id of this PageFeedAssetServiceDownloadJob.  # noqa: E501
        :rtype: int
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this PageFeedAssetServiceDownloadJob.

        <div lang=\"ja\">ジョブIDです。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。</div> <div lang=\"en\">Job ID.<br> Although this field will be returned in the response, it will be ignored on input.</div>   # noqa: E501

        :param job_id: The job_id of this PageFeedAssetServiceDownloadJob.  # noqa: E501
        :type: int
        """

        self._job_id = job_id

    @property
    def progress(self):
        """Gets the progress of this PageFeedAssetServiceDownloadJob.  # noqa: E501

        <div lang=\"ja\">ジョブの進捗状況です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。</div> <div lang=\"en\">Progress of page feed asset job.<br> Although this field will be returned in the response, it will be ignored on input.</div>   # noqa: E501

        :return: The progress of this PageFeedAssetServiceDownloadJob.  # noqa: E501
        :rtype: int
        """
        return self._progress

    @progress.setter
    def progress(self, progress):
        """Sets the progress of this PageFeedAssetServiceDownloadJob.

        <div lang=\"ja\">ジョブの進捗状況です。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。</div> <div lang=\"en\">Progress of page feed asset job.<br> Although this field will be returned in the response, it will be ignored on input.</div>   # noqa: E501

        :param progress: The progress of this PageFeedAssetServiceDownloadJob.  # noqa: E501
        :type: int
        """

        self._progress = progress

    @property
    def start_date(self):
        """Gets the start_date of this PageFeedAssetServiceDownloadJob.  # noqa: E501

        <div lang=\"ja\">ジョブの開始日です。<br>このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 <br> 形式：yyyyMMddHHmmss </div> <div lang=\"en\">Start date of job.<br> Although this field will be returned in the response, it will be ignored on input.<br> Format:yyyyMMddHHmmss</div>   # noqa: E501

        :return: The start_date of this PageFeedAssetServiceDownloadJob.  # noqa: E501
        :rtype: str
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this PageFeedAssetServiceDownloadJob.

        <div lang=\"ja\">ジョブの開始日です。<br>このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 <br> 形式：yyyyMMddHHmmss </div> <div lang=\"en\">Start date of job.<br> Although this field will be returned in the response, it will be ignored on input.<br> Format:yyyyMMddHHmmss</div>   # noqa: E501

        :param start_date: The start_date of this PageFeedAssetServiceDownloadJob.  # noqa: E501
        :type: str
        """

        self._start_date = start_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PageFeedAssetServiceDownloadJob):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PageFeedAssetServiceDownloadJob):
            return True

        return self.to_dict() != other.to_dict()
