# Generated by Django 2.2.5 on 2020-06-25 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("initiatives", "0004_auto_20200624_1547"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiativefile",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="initiativefile",
            name="file",
            field=models.FileField(upload_to="initiatives", verbose_name="Файл"),
        ),
    ]
