# Generated by Django 2.2.5 on 2022-08-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0016_initiativeinstruction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initiative',
            old_name='locality',
            new_name='_locality',
        ),
        migrations.AlterField(
            model_name='initiative',
            name='files',
            field=models.ManyToManyField(to='initiatives.InitiativeFile', verbose_name='Файлы'),
        ),
    ]
