
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-24T11:05:57-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "6f9919b7039ae88ad1b09f0eb46a7aec0e6c4e9b",
 "version": "2.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
