# Generated by Django 2.2.5 on 2020-06-29 10:35

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0008_auto_20200628_1602"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initiative",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("PREMODERATION", "Модерирование"),
                    ("CHANGES_APPROVAL", "Согласование изменений"),
                    ("MODERATION", "Экспертная оценка"),
                    ("REJECTED", "Отклонена"),
                    ("VOTES_COLLECTION", "Сбор голосов"),
                    ("REJECTED_VOTES_THRESHOLD", "Порог голосования не пройден"),
                    ("CONSIDERATION", "На рассмотрении"),
                    ("IN_PROGRESS", "Принято решение"),
                    ("ACCOMPLISHED", "Реализовано"),
                ],
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
