# Generated by Django 2.2.5 on 2020-07-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0012_auto_20200709_1520"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initiativeoperatorcommunication",
            name="type",
            field=models.TextField(
                choices=[
                    ("SYSTEM_NOTIFICATION", "Сообщение системы"),
                    ("PREMODERATE_REQUEST", "Запрос модератора"),
                    ("PREMODERATE_RESPONSE", "Ответ на запрос модератора"),
                    (
                        "PREMODERATE_CHANGES_REQUEST",
                        "Запрос модератора на изменение инициативы",
                    ),
                    (
                        "PREMODERATE_CHANGES_RESPONSE",
                        "Ответ пользователя на изменение инициативы",
                    ),
                    (
                        "PREMODERATE_REJECT",
                        "Инициатива отклонена по решению модератора",
                    ),
                    ("PREMODERATE_APPROVE", "Инициатива одобрена модератором"),
                    ("MODERATE_REQUEST", "Запрос оператора"),
                    ("MODERATE_RESPONSE", "Ответ на запрос оператора"),
                    ("MODERATE_REJECT", "Инициатива отклонена по решению оператора"),
                    (
                        "MODERATE_APPROVE",
                        "Инициатива опубликована по решению оператора",
                    ),
                    ("IN_PROGRESS_NOTIFICATION", "Решение о реализации инициативы"),
                    ("ACCOMPLISHED_NOTIFICATION", "Результаты реализации инициативы"),
                ],
                verbose_name="Тип",
            ),
        ),
    ]
