# Generated by Django 2.2.5 on 2022-08-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20220817_1637'),
        ('initiatives', '0017_auto_20220818_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='locality',
            field=models.ManyToManyField(blank=True, null=True, related_name='initiatives', to='core.Locality', verbose_name='Муниципальные образования'),
        ),
    ]
