# Generated by Django 2.2.5 on 2022-09-06 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0025_auto_20220902_0938'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='initiativeacceptingsettings',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='initiativeacceptingsettings',
            name='_locality',
        ),
    ]
