
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-21T09:55:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "404b79e057ed64377cb834e8ab7757f9c5e03554",
 "version": "2.4.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
