# Generated by Django 2.2.5 on 2020-11-14 02:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0008_auto_20201008_1741"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contractor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Наименование")),
                (
                    "contacts",
                    models.TextField(blank=True, verbose_name="Контактные данные"),
                ),
            ],
            options={
                "verbose_name": "Подрядчик",
                "verbose_name_plural": "Подрядчики",
            },
        ),
        migrations.CreateModel(
            name="InstitutionType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Тип учреждения",
                "verbose_name_plural": "Типы учреждений",
            },
        ),
        migrations.CreateModel(
            name="WorkCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="#000000",
                        max_length=7,
                        null=True,
                        verbose_name="Цвет html",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="(максимальный размер файла 5 МБ)",
                        null=True,
                        upload_to="map",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        help_text="(максимальный размер файла 5 МБ)",
                        null=True,
                        upload_to="map",
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "icon_color",
                    models.CharField(
                        default="#000000", max_length=7, verbose_name="Цвет иконки"
                    ),
                ),
                (
                    "display_after_finish_days",
                    models.PositiveIntegerField(
                        default=1,
                        verbose_name="Отображать на карте после завершения (дней)",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="map_works.WorkCategory",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория работ",
                "verbose_name_plural": "Категории работ",
            },
        ),
        migrations.CreateModel(
            name="WorkReason",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Причина работ",
                "verbose_name_plural": "Причины работ",
            },
        ),
        migrations.CreateModel(
            name="WorkType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Тип работ",
                "verbose_name_plural": "Типы работ",
            },
        ),
        migrations.CreateModel(
            name="Works",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "begin_datetime",
                    models.DateTimeField(verbose_name="Дата/время начала работ"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(verbose_name="Дата/время окончания работ"),
                ),
                (
                    "private_territory",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Частный сектор"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "objects_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание объектов"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="map_works.WorkCategory",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="map_works.Contractor",
                        verbose_name="Подрядчик",
                    ),
                ),
                (
                    "institution_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="map_works.InstitutionType",
                        verbose_name="Тип учреждения",
                    ),
                ),
                (
                    "locality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.Locality",
                        verbose_name="Муниципальное образование",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="map_works.WorkReason",
                        verbose_name="Причина",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="map_works.WorkType",
                        verbose_name="Тип работ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Работы",
                "verbose_name_plural": "Работы",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Адрес"),
                ),
                (
                    "gis_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="Центр"
                    ),
                ),
                (
                    "gis_polygon",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Граница"
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="map_works.Works",
                        verbose_name="Работы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Местоположение",
                "verbose_name_plural": "Местоположения",
            },
        ),
    ]
